-- Generated from reviewed PICKLEBAL PDFs. Unseparated source labels remain pair-only rather than guessed.
create temporary table seed_pickleball_pairs (tournament_slug text, group_name text, pair_name text, source_page integer, organization_code text, member_one text, member_two text) on commit drop;
insert into seed_pickleball_pairs values
  ('doi-nam-31-40','Bảng A','Đặng Mạnh Khang / Nguyễn Đình Nam-PVOIL',1,'PVOIL','Đặng Mạnh Khang','Nguyễn Đình Nam'),
  ('doi-nam-31-40','Bảng A','Nguyễn Đức Hiệp / Trần Minh Châu-PVTRANS',1,'PVTRANS','Nguyễn Đức Hiệp','Trần Minh Châu'),
  ('doi-nam-31-40','Bảng A','Nguyễn Hoàng Nghĩa / Phan Xuân Hoàng-PVD',1,'PVD','Nguyễn Hoàng Nghĩa','Phan Xuân Hoàng'),
  ('doi-nam-31-40','Bảng B','Nguyễn Thượng Nghĩa / Phạm Quang Minh-SWPOC',1,'SWPOC','Nguyễn Thượng Nghĩa','Phạm Quang Minh'),
  ('doi-nam-31-40','Bảng B','Cù Xuân Huy / Trần Nam Trung-PVFCCo',1,'PVFCCo','Cù Xuân Huy','Trần Nam Trung'),
  ('doi-nam-31-40','Bảng B','Ngô Hải Đường / Vũ Đức Hòa-BĐPOC',1,'BĐPOC','Ngô Hải Đường','Vũ Đức Hòa'),
  ('doi-nam-31-40','Bảng C','Bùi Bạch Nhựt / Đặng Văn Hoài Linh- PVMP',2,'PVMP','Bùi Bạch Nhựt','Đặng Văn Hoài Linh'),
  ('doi-nam-31-40','Bảng C','Ngô Bảo Trung / Nguyễn Mạnh Cường-PVOIL',2,'PVOIL','Ngô Bảo Trung','Nguyễn Mạnh Cường'),
  ('doi-nam-31-40','Bảng C','Đoàn Thanh Lâm / Trịnh Minh Tuấn-PV POWER',2,'PV POWER','Đoàn Thanh Lâm','Trịnh Minh Tuấn'),
  ('doi-nam-31-40','Bảng D','Đinh Viết Long / Phạm Ngọc Hải-PVD',2,'PVD','Đinh Viết Long','Phạm Ngọc Hải'),
  ('doi-nam-31-40','Bảng D','Hoàng Ngọc Quý / Nguyễn Minh Tú-PVG',2,'PVG','Hoàng Ngọc Quý','Nguyễn Minh Tú'),
  ('doi-nam-31-40','Bảng D','Nguyễn Bình Phương / Nguyễn Ngọc Thành-PQPOC',2,'PQPOC','Nguyễn Bình Phương','Nguyễn Ngọc Thành'),
  ('doi-nam-31-40','Bảng E','Đoàn Đình Kiên / Ngô Thanh BìnhPV POWER',3,null,null,null),
  ('doi-nam-31-40','Bảng E','Nguyễn Thanh Toàn / Nguyễn Thanh Tùng-PVI',3,'PVI','Nguyễn Thanh Toàn','Nguyễn Thanh Tùng'),
  ('doi-nam-31-40','Bảng E','Nguyễn Hữu Tiến / Võ Thế Cường-VSP',3,'VSP','Nguyễn Hữu Tiến','Võ Thế Cường'),
  ('doi-nam-31-40','Bảng F','Hồ Trọng Khiêm / Phan Sỹ Danh-PVD',3,'PVD','Hồ Trọng Khiêm','Phan Sỹ Danh'),
  ('doi-nam-31-40','Bảng F','Ngô Văn Tuyên / Phạm Văn Nam-PCFCCCo',3,'PCFCCCo','Ngô Văn Tuyên','Phạm Văn Nam'),
  ('doi-nam-31-40','Bảng F','Nguyễn Văn Tráng / Trương Kiên TrungPVG',3,null,null,null),
  ('doi-nam-31-40','Bảng G','Đỗ Xuân Đường / Lê Quang Thái-PVTANS',4,'PVTANS','Đỗ Xuân Đường','Lê Quang Thái'),
  ('doi-nam-31-40','Bảng G','Cao Huy Hiệp / Lê Việt Cường-BĐPOC',4,'BĐPOC','Cao Huy Hiệp','Lê Việt Cường'),
  ('doi-nam-31-40','Bảng G','Đỗ Minh Ngọc / Lê Thành Bi-PVI',4,'PVI','Đỗ Minh Ngọc','Lê Thành Bi'),
  ('doi-nam-31-40','Bảng H','Nguyễn Đức Thuận / Phạm Văn Cường-PVMB',4,'PVMB','Nguyễn Đức Thuận','Phạm Văn Cường'),
  ('doi-nam-31-40','Bảng H','Mai Quang Tú / Trần Đức Anh-VSP',4,'VSP','Mai Quang Tú','Trần Đức Anh'),
  ('doi-nam-31-40','Bảng H','Nguyễn Ngọc Minh / Trần Trung Hiếu-PQPOC',4,'PQPOC','Nguyễn Ngọc Minh','Trần Trung Hiếu'),
  ('doi-nam-31-40','Bảng I','Nguyễn Viết Huy / Tạ Quang Tuấn Anh-PVI',5,'PVI','Nguyễn Viết Huy','Tạ Quang Tuấn Anh'),
  ('doi-nam-31-40','Bảng I','Đỗ Ngọc Vĩnh / Nguyễn Ngọc Khương-NCKHĐT',5,'NCKHĐT','Đỗ Ngọc Vĩnh','Nguyễn Ngọc Khương'),
  ('doi-nam-31-40','Bảng I','Chu Mạnh Hùng / Nguyễn Hữu Nhân-PVEP',5,'PVEP','Chu Mạnh Hùng','Nguyễn Hữu Nhân'),
  ('doi-nam-31-40','Bảng J','Nguyễn Hoàng Phúc / Phan Quang Hùng-PVCom',5,'PVCom','Nguyễn Hoàng Phúc','Phan Quang Hùng'),
  ('doi-nam-31-40','Bảng J','Lê Ngọc Quyết / Võ Thái Sơn-PVCFC',5,'PVCFC','Lê Ngọc Quyết','Võ Thái Sơn'),
  ('doi-nam-31-40','Bảng J','Hồ Trọng Hải / Nguyễn Hoàng Anh-PVTRAS',5,'PVTRAS','Hồ Trọng Hải','Nguyễn Hoàng Anh'),
  ('doi-nam-31-40','Bảng K','Hàn Văn Long / Nguyễn Tiến Dũng-VSP',6,'VSP','Hàn Văn Long','Nguyễn Tiến Dũng'),
  ('doi-nam-31-40','Bảng K','Nguyễn Ngọc Nhã / Trần Ngọc Trung-BĐPOC',6,'BĐPOC','Nguyễn Ngọc Nhã','Trần Ngọc Trung'),
  ('doi-nam-31-40','Bảng K','Trần Quốc Khương / Trần Việt Linh-PVMB',6,'PVMB','Trần Quốc Khương','Trần Việt Linh'),
  ('doi-nam-31-40','Bảng L','Lê Quyết Chiến / Nguyễn Công Hoàng-PET',6,'PET','Lê Quyết Chiến','Nguyễn Công Hoàng'),
  ('doi-nam-31-40','Bảng L','Huỳnh My Lai / Vũ Đức An-PVComBank',6,'PVComBank','Huỳnh My Lai','Vũ Đức An'),
  ('doi-nam-31-40','Bảng L','Bùi Tuấn Anh / Nguyễn Thành Luân-PVEP',6,'PVEP','Bùi Tuấn Anh','Nguyễn Thành Luân'),
  ('doi-nam-41-50','Bảng A','Phan Ngọc Quyết / Trương Tấn Lợi-VSP',1,'VSP','Phan Ngọc Quyết','Trương Tấn Lợi'),
  ('doi-nam-41-50','Bảng A','Bùi Quang Hưng / Nguyễn Quốc HuyPVTRANS',1,null,null,null),
  ('doi-nam-41-50','Bảng A','Nguyễn Văn Tuyên / Trần Nghĩa Anh-PVOIL',1,'PVOIL','Nguyễn Văn Tuyên','Trần Nghĩa Anh'),
  ('doi-nam-41-50','Bảng A','Đặng Văn Tuấn / Nguyễn Ngọc Sơn-PQPOC',1,'PQPOC','Đặng Văn Tuấn','Nguyễn Ngọc Sơn'),
  ('doi-nam-41-50','Bảng B','Nguyễn Ngọc Vũ / Ng Xuân Trường-PV POWER',2,'PV POWER','Nguyễn Ngọc Vũ','Ng Xuân Trường'),
  ('doi-nam-41-50','Bảng B','Đặng Huy Tài / Phan Văn Quang-PVFCCo',2,'PVFCCo','Đặng Huy Tài','Phan Văn Quang'),
  ('doi-nam-41-50','Bảng B','Chu Minh Hòa / Lê Trọng Nhân-SWPOC',2,'SWPOC','Chu Minh Hòa','Lê Trọng Nhân'),
  ('doi-nam-41-50','Bảng B','Đoàn Lê Dũng / Nguyễn Công Cường-PET',2,'PET','Đoàn Lê Dũng','Nguyễn Công Cường'),
  ('doi-nam-41-50','Bảng C','Hoàng Xuân Thoả / Nguyễn Thanh Bằng-PVFCCo',3,'PVFCCo','Hoàng Xuân Thoả','Nguyễn Thanh Bằng'),
  ('doi-nam-41-50','Bảng C','Lê Đình Biên / Trần Tuấn An-SWPOC',3,'SWPOC','Lê Đình Biên','Trần Tuấn An'),
  ('doi-nam-41-50','Bảng C','Lê Văn Thảo / Ngô Minh Hoàng-PVI',3,'PVI','Lê Văn Thảo','Ngô Minh Hoàng'),
  ('doi-nam-41-50','Bảng C','Lê Việt Thường / Nguyễn Mậu Đăng-PVFCCo',3,'PVFCCo','Lê Việt Thường','Nguyễn Mậu Đăng'),
  ('doi-nam-41-50','Bảng D','Hoàng Văn Mạnh / Nguyễn Đình Chung-NCKHĐT',4,'NCKHĐT','Hoàng Văn Mạnh','Nguyễn Đình Chung'),
  ('doi-nam-41-50','Bảng D','Nguyễn Văn Tiến / Trịnh Huy Thắng-PVCCHEM',4,'PVCCHEM','Nguyễn Văn Tiến','Trịnh Huy Thắng'),
  ('doi-nam-41-50','Bảng D','Nguyễn Hoàng Anh / Nguyễn Thành Ba- VSP',4,'VSP','Nguyễn Hoàng Anh','Nguyễn Thành Ba'),
  ('doi-nam-41-50','Bảng D','Lê Minh Phong / Trần Hoàng Minh-PETROCONs',4,'PETROCONs','Lê Minh Phong','Trần Hoàng Minh'),
  ('doi-nam-41-50','Bảng E','Hoàng Hiệp / Nguyễn Duy Hân-PVOIL',5,'PVOIL','Hoàng Hiệp','Nguyễn Duy Hân'),
  ('doi-nam-41-50','Bảng E','Hồ Sỹ Chương / Nguyễn Xuân Thủy-PVEP',5,'PVEP','Hồ Sỹ Chương','Nguyễn Xuân Thủy'),
  ('doi-nam-41-50','Bảng E','Nguyễn Văn Nhung / Phạm Duy Ngọc-PVFCCo',5,'PVFCCo','Nguyễn Văn Nhung','Phạm Duy Ngọc'),
  ('doi-nam-41-50','Bảng E','Đỗ Văn Tài / Nguyễn Việt Cường-PVCHEM',5,'PVCHEM','Đỗ Văn Tài','Nguyễn Việt Cường'),
  ('doi-nam-41-50','Bảng F','Đặng Quang Tuân / Đinh Trần Trung Kiên-BĐPOC',6,'BĐPOC','Đặng Quang Tuân','Đinh Trần Trung Kiên'),
  ('doi-nam-41-50','Bảng F','Nguyễn Văn Sơn / Phạm Văn Thu-PETOCONs',6,'PETOCONs','Nguyễn Văn Sơn','Phạm Văn Thu'),
  ('doi-nam-41-50','Bảng F','Vũ Anh Tuấn / Vũ Quý Hoàng-VSP',6,'VSP','Vũ Anh Tuấn','Vũ Quý Hoàng'),
  ('doi-nam-41-50','Bảng F','Bùi Tử An / Dương Chí Trung-NCKHĐT',6,'NCKHĐT','Bùi Tử An','Dương Chí Trung'),
  ('doi-nam-41-50','Bảng G','Bùi Ngọc Quyền / Lê Việt Dũng -BĐPOC',7,'BĐPOC','Bùi Ngọc Quyền','Lê Việt Dũng'),
  ('doi-nam-41-50','Bảng G','Hoàng Minh Hưng / Nguyễn Tiến Lợi-PQPOC',7,'PQPOC','Hoàng Minh Hưng','Nguyễn Tiến Lợi'),
  ('doi-nam-41-50','Bảng G','Nguyễn Văn Đồng / Phạm Quốc Thành-PVCHEM',7,'PVCHEM','Nguyễn Văn Đồng','Phạm Quốc Thành'),
  ('doi-nam-41-50','Bảng G','Đỗ Trung Thành / Trần Đình Niên- PET',7,'PET','Đỗ Trung Thành','Trần Đình Niên'),
  ('doi-nam-41-50','Bảng H','Hà Minh Tuấn / Nguyễn Hồng Giang-PVD',8,'PVD','Hà Minh Tuấn','Nguyễn Hồng Giang'),
  ('doi-nam-41-50','Bảng H','Nguyễn Thanh Hà / Thái Đào Tuấn Khanh-BĐPOC',8,'BĐPOC','Nguyễn Thanh Hà','Thái Đào Tuấn Khanh'),
  ('doi-nam-41-50','Bảng H','Lê Thanh Tùng / Trần Văn Thực-PVOIL',8,'PVOIL','Lê Thanh Tùng','Trần Văn Thực'),
  ('doi-nam-41-50','Bảng H','Hồ Anh Khoa / Phạm Chính Hiếu-SWPOC',8,'SWPOC','Hồ Anh Khoa','Phạm Chính Hiếu'),
  ('doi-nam-41-50','Bảng I','Hoàng Quốc Thành Huy / Tường Duy Quân-PVMR',9,'PVMR','Hoàng Quốc Thành Huy','Tường Duy Quân'),
  ('doi-nam-41-50','Bảng I','Nguyễn Văn Bảo / Thới Thành Phủ-PV combank',9,'PV combank','Nguyễn Văn Bảo','Thới Thành Phủ'),
  ('doi-nam-41-50','Bảng I','Dương Bình / Phan Văn Hảo-PVEP',9,'PVEP','Dương Bình','Phan Văn Hảo'),
  ('doi-nam-41-50','Bảng I','Đặng Quốc PhonG / Võ khắc Anh Vũ-PQPOC',9,'PQPOC','Đặng Quốc PhonG','Võ khắc Anh Vũ'),
  ('doi-nam-tren-51','Bảng A','Lê Kim Long / Lê Trần Hòa-NCKHĐT',1,'NCKHĐT','Lê Kim Long','Lê Trần Hòa'),
  ('doi-nam-tren-51','Bảng A','Hoàng Đức Tuấn / Nguyễn Văn Ánh-VSP',1,'VSP','Hoàng Đức Tuấn','Nguyễn Văn Ánh'),
  ('doi-nam-tren-51','Bảng A','Hà Thân Tín / Nguyễn Công Ngọc-PET',1,'PET','Hà Thân Tín','Nguyễn Công Ngọc'),
  ('doi-nam-tren-51','Bảng B','Nguyễn Tiến Hải / Nguyễn Văn Đức-PVG',1,'PVG','Nguyễn Tiến Hải','Nguyễn Văn Đức'),
  ('doi-nam-tren-51','Bảng B','Hồ Trọng Lục / Nguyễn Ánh Sao-PVOIL',1,'PVOIL','Hồ Trọng Lục','Nguyễn Ánh Sao'),
  ('doi-nam-tren-51','Bảng B','Nguyễn Thế Đường / Nguyễn Viết Vượng-PVEP',1,'PVEP','Nguyễn Thế Đường','Nguyễn Viết Vượng'),
  ('doi-nam-tren-51','Bảng C','Lê Văn Xương / Vũ Đình Thu-BĐPOC',2,'BĐPOC','Lê Văn Xương','Vũ Đình Thu'),
  ('doi-nam-tren-51','Bảng C','An Quốc Hưng / Trần Hải Đăng-PVFC',2,'PVFC','An Quốc Hưng','Trần Hải Đăng'),
  ('doi-nam-tren-51','Bảng C','Lê Mạnh Hùng / Nguyễn Tiến Sỹ-PVFCCo',2,'PVFCCo','Lê Mạnh Hùng','Nguyễn Tiến Sỹ'),
  ('doi-nam-tren-51','Bảng D','Phạm Anh Ninh / Phạm Văn Hiến-BĐPOC',2,'BĐPOC','Phạm Anh Ninh','Phạm Văn Hiến'),
  ('doi-nam-tren-51','Bảng D','Nguyễn Văn Thái / Phan Đức Trung-PVG',2,'PVG','Nguyễn Văn Thái','Phan Đức Trung'),
  ('doi-nam-tren-51','Bảng D','Châu Thanh Lễ / Trần Thanh Hải-SWPOC',2,'SWPOC','Châu Thanh Lễ','Trần Thanh Hải'),
  ('doi-nam-tren-51','Bảng D','Nguyễn Phan Trí / Phạm Thanh Hưng-NCKHĐT',2,'NCKHĐT','Nguyễn Phan Trí','Phạm Thanh Hưng'),
  ('doi-nam-tren-51','Bảng E','Nguyễn Ngọc Minh / Vũ Minh Đức-PVEP',3,'PVEP','Nguyễn Ngọc Minh','Vũ Minh Đức'),
  ('doi-nam-tren-51','Bảng E','Lê Hồng Hải / Trần Huy Thực-PVG',3,'PVG','Lê Hồng Hải','Trần Huy Thực'),
  ('doi-nam-tren-51','Bảng E','Nguyễn Minh Tân / Trần Hồng Phong- PVMR',3,'PVMR','Nguyễn Minh Tân','Trần Hồng Phong'),
  ('doi-nam-tren-51','Bảng F','Nguyễn Thu Phong / Trần Anh Đức-PVOIL',4,'PVOIL','Nguyễn Thu Phong','Trần Anh Đức'),
  ('doi-nam-tren-51','Bảng F','Ngô Đình Chung / Nguyễn Thanh Tịnh-VSP',4,'VSP','Ngô Đình Chung','Nguyễn Thanh Tịnh'),
  ('doi-nam-tren-51','Bảng F','Đinh Minh Tú / Hồ Trường Giang-PVTRANS',4,'PVTRANS','Đinh Minh Tú','Hồ Trường Giang'),
  ('doi-nam-tren-51','Bảng G','Huỳnh Tuấn Kiệt / Nguyễn Quang Vinh-PQPOC',4,'PQPOC','Huỳnh Tuấn Kiệt','Nguyễn Quang Vinh'),
  ('doi-nam-tren-51','Bảng G','Phạm Văn Đoàn / Trịnh Văn Đạo-VSP',4,'VSP','Phạm Văn Đoàn','Trịnh Văn Đạo'),
  ('doi-nam-tren-51','Bảng G','Phạm Xuân Hồng / Trần Văn Hùng-PVOIL',4,'PVOIL','Phạm Xuân Hồng','Trần Văn Hùng'),
  ('doi-nam-tren-51','Bảng H','Bùi Trung Kiên / Nguyễn Văn Sang-PTSC',5,'PTSC','Bùi Trung Kiên','Nguyễn Văn Sang'),
  ('doi-nam-tren-51','Bảng H','Lê Hôǹ g Lĩnh / Nguyễn Văn Hải-PVEP',5,'PVEP','Lê Hôǹ g Lĩnh','Nguyễn Văn Hải'),
  ('doi-nam-tren-51','Bảng H','Nguyễn Hữu Lễ / Trần Dũng Tiến-PV POWER',5,'PV POWER','Nguyễn Hữu Lễ','Trần Dũng Tiến'),
  ('doi-nam-tren-51','Bảng H','Đỗ Đoàn Tấn Tài / Ngô Ngọc Trung-PVFCCo',5,'PVFCCo','Đỗ Đoàn Tấn Tài','Ngô Ngọc Trung'),
  ('doi-nam-nu-duoi-30','Bảng A','Hoàng Linh Anh / Trần Anh Duy-PVOIL',1,'PVOIL','Hoàng Linh Anh','Trần Anh Duy'),
  ('doi-nam-nu-duoi-30','Bảng A','Lê Hoài Bắc / Nguyễn Hoàng Anh-PVG',1,'PVG','Lê Hoài Bắc','Nguyễn Hoàng Anh'),
  ('doi-nam-nu-duoi-30','Bảng A','Long Thị Yến Nhi / Vũ Văn Tuấn-PVComBank',1,'PVComBank','Long Thị Yến Nhi','Vũ Văn Tuấn'),
  ('doi-nam-nu-duoi-30','Bảng B','Huỳnh Thanh Quỳnh Nhi / Lê Khánh Huy-VSP',1,'VSP','Huỳnh Thanh Quỳnh Nhi','Lê Khánh Huy'),
  ('doi-nam-nu-duoi-30','Bảng B','Đỗ Đình Ngọc Tùng / Phan Thị Kim Ngân-PVFCCo',1,'PVFCCo','Đỗ Đình Ngọc Tùng','Phan Thị Kim Ngân'),
  ('doi-nam-nu-duoi-30','Bảng B','Lê Thị Tường Vi / Trần Hữu Đăng Khoa-PVTRANS',1,'PVTRANS','Lê Thị Tường Vi','Trần Hữu Đăng Khoa'),
  ('doi-nam-nu-duoi-30','Bảng C','Nguyễn Hữu Lam / Nguyễn Thị Diễm Phúc-PVFCCo',2,'PVFCCo','Nguyễn Hữu Lam','Nguyễn Thị Diễm Phúc'),
  ('doi-nam-nu-duoi-30','Bảng C','Ngo Hoai Nam / Võ Thị Thuỳ Linh-PQPOC',2,'PQPOC','Ngo Hoai Nam','Võ Thị Thuỳ Linh'),
  ('doi-nam-nu-duoi-30','Bảng C','Bùi Văn Quảng / Phan Thị Tuyết Ngân-PV POWER',2,'PV POWER','Bùi Văn Quảng','Phan Thị Tuyết Ngân'),
  ('doi-nam-nu-duoi-30','Bảng D','Quách Văn Kiệt / Trương Lê Ngọc Trinh-PET',2,'PET','Quách Văn Kiệt','Trương Lê Ngọc Trinh'),
  ('doi-nam-nu-duoi-30','Bảng D','Hoàng Quốc Bảo / Tăng Kim Thụy Vi-PVTRANS',2,'PVTRANS','Hoàng Quốc Bảo','Tăng Kim Thụy Vi'),
  ('doi-nam-nu-duoi-30','Bảng D','Nguyễn Quốc Khởi/Phạm Thị Hương-PVG',2,'PVG','Nguyễn Quốc Khởi','Phạm Thị Hương'),
  ('doi-nam-nu-duoi-30','Bảng E','Nguyễn Hải Anh / Trương Hoàng Ngọc-PVOIL',3,'PVOIL','Nguyễn Hải Anh','Trương Hoàng Ngọc'),
  ('doi-nam-nu-duoi-30','Bảng E','Đỗ Thị Mai Trang / Vũ Hùng Anh-VSP',3,'VSP','Đỗ Thị Mai Trang','Vũ Hùng Anh'),
  ('doi-nam-nu-duoi-30','Bảng E','Lê Văn Tuấn / Trịnh Thị Hiền-PTSC',3,'PTSC','Lê Văn Tuấn','Trịnh Thị Hiền'),
  ('doi-nam-nu-duoi-30','Bảng F','Bùi Thanh Toàn / Lê Thị Nhung-NCKHĐT',3,'NCKHĐT','Bùi Thanh Toàn','Lê Thị Nhung'),
  ('doi-nam-nu-duoi-30','Bảng F','Đặng Thị Quỳnh / Nguyễn Tiến Hiểu-PVG',3,'PVG','Đặng Thị Quỳnh','Nguyễn Tiến Hiểu'),
  ('doi-nam-nu-duoi-30','Bảng F','Nguyễn Thị Hậu / Phan Văn Tứ--PVcomBank',3,'PVcomBank','Nguyễn Thị Hậu','Phan Văn Tứ-'),
  ('doi-nam-nu-duoi-30','Bảng G','Lê Thị Hiền / Trần Tuấn Anh-PVD',4,'PVD','Lê Thị Hiền','Trần Tuấn Anh'),
  ('doi-nam-nu-duoi-30','Bảng G','Nghiêm Viết Quang / Phạm Thị Hồng- PVEP',4,'PVEP','Nghiêm Viết Quang','Phạm Thị Hồng'),
  ('doi-nam-nu-duoi-30','Bảng G','Hoàng Lưu Thúy Nga / Ngô Huy Long-VSP',4,'VSP','Hoàng Lưu Thúy Nga','Ngô Huy Long'),
  ('doi-nam-nu-duoi-30','Bảng G','Bùi Quang Thanh / Phạm Thị Phương Dung- PVMR',4,'PVMR','Bùi Quang Thanh','Phạm Thị Phương Dung'),
  ('doi-nam-nu-31-40','Bảng A','Bùi Duy Thành / Hoàng Khánh Huyền-PVTRANS',1,'PVTRANS','Bùi Duy Thành','Hoàng Khánh Huyền'),
  ('doi-nam-nu-31-40','Bảng A','Bùi Thanh Việt/ Mai thanh Trâm-PVG',1,'PVG','Bùi Thanh Việt','Mai thanh Trâm'),
  ('doi-nam-nu-31-40','Bảng A','Lê Nam / Vũ Thị Hoài Thu-PVMR',1,'PVMR','Lê Nam','Vũ Thị Hoài Thu'),
  ('doi-nam-nu-31-40','Bảng A','Nguyễn Thành Công / Trần Thị Thanh Huyền- VSP',1,'VSP','Nguyễn Thành Công','Trần Thị Thanh Huyền'),
  ('doi-nam-nu-31-40','Bảng B','Nguyễn Thị Phượng / Nguyễn Văn Quế-PVcomBank',1,'PVcomBank','Nguyễn Thị Phượng','Nguyễn Văn Quế'),
  ('doi-nam-nu-31-40','Bảng B','Thái Thiên Thanh / Vũ Quang Hiển-PVOIL',1,'PVOIL','Thái Thiên Thanh','Vũ Quang Hiển'),
  ('doi-nam-nu-31-40','Bảng B','Đỗ Thị Quỳnh Trang / Nguyễn Thanh Tâm-BĐPOC',1,'BĐPOC','Đỗ Thị Quỳnh Trang','Nguyễn Thanh Tâm'),
  ('doi-nam-nu-31-40','Bảng B','Nguyễn Thị Loan / Trần Quốc AnhPVCHEM',1,null,null,null),
  ('doi-nam-nu-31-40','Bảng C','Bùi Anh Tuấn / Nguyễn Hải Nguyên-PVMB',2,'PVMB','Bùi Anh Tuấn','Nguyễn Hải Nguyên'),
  ('doi-nam-nu-31-40','Bảng C','Lê thị Tường Vi/ Ng Hoang Minh- / PVTRANS',2,'PVTRANS','Lê thị Tường Vi','Ng Hoang Minh'),
  ('doi-nam-nu-31-40','Bảng C','Đặng Thùy Chi / Vũ Tiến Trung- PVEP',2,'PVEP','Đặng Thùy Chi','Vũ Tiến Trung'),
  ('doi-nam-nu-31-40','Bảng C','Đoàn Khánh Trình / Phạm Thị Thu Hiên-PVG',2,'PVG','Đoàn Khánh Trình','Phạm Thị Thu Hiên'),
  ('doi-nam-nu-31-40','Bảng D','Hồ Văn Linh / Phan Thị Thu-PETRCONs',2,'PETRCONs','Hồ Văn Linh','Phan Thị Thu'),
  ('doi-nam-nu-31-40','Bảng D','Lê Thị Hà / Nguyễn Ngọc Anh- VSP',2,'VSP','Lê Thị Hà','Nguyễn Ngọc Anh'),
  ('doi-nam-nu-31-40','Bảng D','Như Ý Nguyễn / Vũ Chí Cường-PQPOC',2,'PQPOC','Như Ý Nguyễn','Vũ Chí Cường'),
  ('doi-nam-nu-31-40','Bảng D','Phạm Thị Mơ / Phan Ngọc Khánh-PVTRANS',2,'PVTRANS','Phạm Thị Mơ','Phan Ngọc Khánh'),
  ('doi-nam-nu-31-40','Bảng E','Mai Bảo Ngọc / Vũ Đức Thành-PVMR',3,'PVMR','Mai Bảo Ngọc','Vũ Đức Thành'),
  ('doi-nam-nu-31-40','Bảng E','Doãn Thị Yến / Đỗ Văn Việt- POWER',3,'POWER','Doãn Thị Yến','Đỗ Văn Việt'),
  ('doi-nam-nu-31-40','Bảng E','Nguyễn Thùy Phương / Phan Huy Bình-BĐPOC',3,'BĐPOC','Nguyễn Thùy Phương','Phan Huy Bình'),
  ('doi-nam-nu-31-40','Bảng E','Lê Thị Thùy Dung / Võ Tiến Dũng-PVCFC',3,'PVCFC','Lê Thị Thùy Dung','Võ Tiến Dũng'),
  ('doi-nam-nu-31-40','Bảng F','Nguyễn Tân Huyền / Nguyễn Thị Thảo- BMĐH',3,'BMĐH','Nguyễn Tân Huyền','Nguyễn Thị Thảo'),
  ('doi-nam-nu-31-40','Bảng F','Nguyễn Thị Bích Liễu / Trần Quốc Vương-PVcomBank',3,'PVcomBank','Nguyễn Thị Bích Liễu','Trần Quốc Vương'),
  ('doi-nam-nu-31-40','Bảng F','Nguyễn Thị Hoài Thương / Nguyễn Văn Bính-VSP',3,'VSP','Nguyễn Thị Hoài Thương','Nguyễn Văn Bính'),
  ('doi-nam-nu-31-40','Bảng F','Nguyễn Thị Thanh Huyền / Phạm Phú Quốc-PVD',3,'PVD','Nguyễn Thị Thanh Huyền','Phạm Phú Quốc'),
  ('doi-nam-nu-31-40','Bảng G','Châu Khiếu Minh / Nguyễn Thị Thanh -NCKHĐT',4,'NCKHĐT','Châu Khiếu Minh','Nguyễn Thị Thanh'),
  ('doi-nam-nu-31-40','Bảng G','Nguyễn Thị Ngọc Mai / Vũ Xuân HưngPVG',4,null,null,null),
  ('doi-nam-nu-31-40','Bảng G','Lê Hoàng / Ngô Bích Ngọc-PVMR',4,'PVMR','Lê Hoàng','Ngô Bích Ngọc'),
  ('doi-nam-nu-31-40','Bảng G','Lê Thị Ngọc Lan / Nguyễn Hoàng Long-PV POWER',4,'PV POWER','Lê Thị Ngọc Lan','Nguyễn Hoàng Long'),
  ('doi-nam-nu-31-40','Bảng H','Bùi Thị Hà / Võ Hoàng Long- PET',4,'PET','Bùi Thị Hà','Võ Hoàng Long'),
  ('doi-nam-nu-31-40','Bảng H','Mai Minh Phương / Phạm Thị Gấm-PVFCCo',4,'PVFCCo','Mai Minh Phương','Phạm Thị Gấm'),
  ('doi-nam-nu-31-40','Bảng H','Nguyễn Hồng Cẩm Nhung / Trương Ngọc CườngPVCHEM',4,null,null,null),
  ('doi-nam-nu-41-50','Bảng A','Hoàng Thị Ngân / Võ Thanh Tịnh-PETROCONs',1,'PETROCONs','Hoàng Thị Ngân','Võ Thanh Tịnh'),
  ('doi-nam-nu-41-50','Bảng A','Bùi Thị Phương Nam / Nguyễn Ngọc Phương-PVCHEM',1,'PVCHEM','Bùi Thị Phương Nam','Nguyễn Ngọc Phương'),
  ('doi-nam-nu-41-50','Bảng A','Nguyễn Thị Hoa / Trần Đức Minh-PVEP',1,'PVEP','Nguyễn Thị Hoa','Trần Đức Minh'),
  ('doi-nam-nu-41-50','Bảng B','Mai Thị Bích Thảo / Nguyễn Văn Tình-BMĐH',1,'BMĐH','Mai Thị Bích Thảo','Nguyễn Văn Tình'),
  ('doi-nam-nu-41-50','Bảng B','Bùi Thị Ngọc Lan / Phạm Văn Dương-PTSC',1,'PTSC','Bùi Thị Ngọc Lan','Phạm Văn Dương'),
  ('doi-nam-nu-41-50','Bảng B','Trần Bích Thùy / Trần Thanh Huy-NCKH',1,'NCKH','Trần Bích Thùy','Trần Thanh Huy'),
  ('doi-nam-nu-41-50','Bảng C','Đỗ Thành Trung / Nguyễn Thị Anh Thảo-PVCFC',2,'PVCFC','Đỗ Thành Trung','Nguyễn Thị Anh Thảo'),
  ('doi-nam-nu-41-50','Bảng C','Đoàn Văn Cương / Nguyễn Thị Thùy Dương-PVPMB',2,'PVPMB','Đoàn Văn Cương','Nguyễn Thị Thùy Dương'),
  ('doi-nam-nu-41-50','Bảng C','Bùi Thị Tố Loan / Lê Văn Đồng-PET',2,'PET','Bùi Thị Tố Loan','Lê Văn Đồng'),
  ('doi-nam-nu-41-50','Bảng D','Nguyễn Thị Thảo / Trần Sơn Anh-VSP',2,'VSP','Nguyễn Thị Thảo','Trần Sơn Anh'),
  ('doi-nam-nu-41-50','Bảng D','Nguyễn Như Trường / Phạm Thị Trang Vân-NCKH',2,'NCKH','Nguyễn Như Trường','Phạm Thị Trang Vân'),
  ('doi-nam-nu-41-50','Bảng D','Bùi Hải Bình / Vũ Lê Thu Trang-PVOIL',2,'PVOIL','Bùi Hải Bình','Vũ Lê Thu Trang'),
  ('doi-nam-nu-41-50','Bảng E','Lê Thu Trang / Nguyễn Tuấn Anh-VSP',3,'VSP','Lê Thu Trang','Nguyễn Tuấn Anh'),
  ('doi-nam-nu-41-50','Bảng E','Nguyễn Thị Thu Hiền / Nguyễn Văn Sáu-PVEP',3,'PVEP','Nguyễn Thị Thu Hiền','Nguyễn Văn Sáu'),
  ('doi-nam-nu-41-50','Bảng E','Bùi Mạnh Linh / Lý Thúy An-BĐPOC',3,'BĐPOC','Bùi Mạnh Linh','Lý Thúy An'),
  ('doi-nam-nu-41-50','Bảng F','Lê Thị Trang / Trần Hữu Trung-PVMR',3,'PVMR','Lê Thị Trang','Trần Hữu Trung'),
  ('doi-nam-nu-41-50','Bảng F','Nguyễn Văn Dũng / Phạm Thị Hồng Hiền-VSP',3,'VSP','Nguyễn Văn Dũng','Phạm Thị Hồng Hiền'),
  ('doi-nam-nu-41-50','Bảng F','Tạ Hải Nam / Trần Thị Hoàng Mai-BĐPOC',3,'BĐPOC','Tạ Hải Nam','Trần Thị Hoàng Mai'),
  ('doi-nam-nu-41-50','Bảng G','Đậu Phi Công / Lê Thị Thanh Hà-PVOIL',4,'PVOIL','Đậu Phi Công','Lê Thị Thanh Hà'),
  ('doi-nam-nu-41-50','Bảng G','Bùi Thị Thúy Vượng / Nguyễn Xuân Phường-PVEP',4,'PVEP','Bùi Thị Thúy Vượng','Nguyễn Xuân Phường'),
  ('doi-nam-nu-41-50','Bảng G','Đoàn Văn Trường / Khổng Thị Ái Xuân-PVFCCo',4,'PVFCCo','Đoàn Văn Trường','Khổng Thị Ái Xuân'),
  ('doi-nam-duoi-30','Bảng A','Hồ Xuân Hảo / Trần Đại Thiệu-VSP',1,'VSP','Hồ Xuân Hảo','Trần Đại Thiệu'),
  ('doi-nam-duoi-30','Bảng A','Lê Đăng Tú / Trần Hữu Long-PVFCCo',1,'PVFCCo','Lê Đăng Tú','Trần Hữu Long'),
  ('doi-nam-duoi-30','Bảng A','Nguyễn Đức Hùng / Nguyễn Hải BiênPQPOC',1,null,null,null),
  ('doi-nam-duoi-30','Bảng B','Nguyễn Văn Tú / Phạm Văn Hưng-PVFCCo',1,'PVFCCo','Nguyễn Văn Tú','Phạm Văn Hưng'),
  ('doi-nam-duoi-30','Bảng B','Nguyễn Hoàng Văn / Nguyễn Nhật Minh-PVG',1,'PVG','Nguyễn Hoàng Văn','Nguyễn Nhật Minh'),
  ('doi-nam-duoi-30','Bảng B','Đoàn Văn Chúc / Nguyễn Trọng NhânLP1PP',1,null,null,null),
  ('doi-nam-duoi-30','Bảng C','Nguyễn Minh Tuấn / Trần Công Lê Thắng-VSP',2,'VSP','Nguyễn Minh Tuấn','Trần Công Lê Thắng'),
  ('doi-nam-duoi-30','Bảng C','Giáp Văn Tuấn / Hoàng Đình Cương PET',2,null,null,null),
  ('doi-nam-duoi-30','Bảng C','Nguyễn Đức Anh / Nguyễn Văn Sửu-PVCHEM',2,'PVCHEM','Nguyễn Đức Anh','Nguyễn Văn Sửu'),
  ('doi-nam-duoi-30','Bảng D','Lê Quốc Truyền / Trần Minh Hiếu-PVI HOLIDINGS',2,'PVI HOLIDINGS','Lê Quốc Truyền','Trần Minh Hiếu'),
  ('doi-nam-duoi-30','Bảng D','Bùi Tiến Thành / Trần Thái-PVTRAN',2,'PVTRAN','Bùi Tiến Thành','Trần Thái'),
  ('doi-nam-duoi-30','Bảng D','Huỳnh Hữu Đức / Lê Thanh Bình-PVEP',2,'PVEP','Huỳnh Hữu Đức','Lê Thanh Bình'),
  ('doi-nam-duoi-30','Bảng E','Đỗ Văn Dương / Trương Hoài Phi-PVD',3,'PVD','Đỗ Văn Dương','Trương Hoài Phi'),
  ('doi-nam-duoi-30','Bảng E','Đỗ Hoàng Nam / Lê Thiện Nhật-PVTRANS',3,'PVTRANS','Đỗ Hoàng Nam','Lê Thiện Nhật'),
  ('doi-nam-duoi-30','Bảng E','Lê Quốc Việt Anh / Nguyễn Văn Chung-PVOIL',3,'PVOIL','Lê Quốc Việt Anh','Nguyễn Văn Chung'),
  ('doi-nam-duoi-30','Bảng F','Nguyễn Xuân Ngọc / Phạm Quang Hiếu-PVE',3,'PVE','Nguyễn Xuân Ngọc','Phạm Quang Hiếu'),
  ('doi-nam-duoi-30','Bảng F','Trần Đình Vũ / Trịnh Ngọc Vương-PVCFC',3,'PVCFC','Trần Đình Vũ','Trịnh Ngọc Vương'),
  ('doi-nam-duoi-30','Bảng F','Cao Ngọc Tuấn / Lê Trọng Nghĩa-PVEP',3,'PVEP','Cao Ngọc Tuấn','Lê Trọng Nghĩa'),
  ('doi-nam-duoi-30','Bảng G','Nguyễn Hùng Cường / Nguyễn Minh ThuậnPVPOWER',4,null,null,null),
  ('doi-nam-duoi-30','Bảng G','Trần Hữu Đăng Khoa/Phạm Đức Trọng-PVTRANS',4,'PVTRANS','Trần Hữu Đăng Khoa','Phạm Đức Trọng'),
  ('doi-nam-duoi-30','Bảng G','lương thúc chính / Nguyễn Minh Hải-PQPOC',4,'PQPOC','lương thúc chính','Nguyễn Minh Hải'),
  ('doi-nam-duoi-30','Bảng H','Nguyễn Duy Hùng / Trịnh Đăng Tấn-PQPOC',4,'PQPOC','Nguyễn Duy Hùng','Trịnh Đăng Tấn'),
  ('doi-nam-duoi-30','Bảng H','Đặng Văn Tùng / Nguyễn Huy Hoàng-PVD',4,'PVD','Đặng Văn Tùng','Nguyễn Huy Hoàng'),
  ('doi-nam-duoi-30','Bảng H','Bùi Trọng Toàn / Tạ Văn Quyǹ h-VSP',4,'VSP','Bùi Trọng Toàn','Tạ Văn Quyǹ h'),
  ('doi-nam-duoi-30','Bảng I','Nguyễn Hoàng Quý / Nguyễn Thanh Tuấn-PVD',5,'PVD','Nguyễn Hoàng Quý','Nguyễn Thanh Tuấn'),
  ('doi-nam-duoi-30','Bảng I','Nguyễn Mạnh Hưng / Nguyễn Xuân Hiến-BĐPOC',5,'BĐPOC','Nguyễn Mạnh Hưng','Nguyễn Xuân Hiến'),
  ('doi-nam-duoi-30','Bảng I','Nguyễn Hùng Binh / Nguyễn Minh Thuấn-PVCHEM',5,'PVCHEM','Nguyễn Hùng Binh','Nguyễn Minh Thuấn'),
  ('doi-nam-duoi-30','Bảng J','Phạm Văn Huỳnh / Trần Xuân Cảnh-PCOIL',5,'PCOIL','Phạm Văn Huỳnh','Trần Xuân Cảnh'),
  ('doi-nam-duoi-30','Bảng J','Hoàng Đình Phong / Vũ Xuân An-PVG',5,'PVG','Hoàng Đình Phong','Vũ Xuân An'),
  ('doi-nam-duoi-30','Bảng K','Bùi Khắc Anh Tuấn / Phạm Hồng Phương-PET',6,'PET','Bùi Khắc Anh Tuấn','Phạm Hồng Phương'),
  ('doi-nam-duoi-30','Bảng K','Bùi Ngô Phúc Minh / Đặng Việt An-MNĐH PETRO',6,'MNĐH PETRO','Bùi Ngô Phúc Minh','Đặng Việt An'),
  ('doi-nam-duoi-30','Bảng K','Bùi Trung Kiên / Phan Phước Gia-PVEP',6,'PVEP','Bùi Trung Kiên','Phan Phước Gia'),
  ('doi-nu-31-40','Bảng A','Lê Thúy Nga / Nguyễn Thị Bích Liên-VSP',1,'VSP','Lê Thúy Nga','Nguyễn Thị Bích Liên'),
  ('doi-nu-31-40','Bảng A','Đinh Ngân Đài / Nguyễn Thùy Chi-PVEP',1,'PVEP','Đinh Ngân Đài','Nguyễn Thùy Chi'),
  ('doi-nu-31-40','Bảng A','Bùi Thanh Kim Ngọc / Lê Thị Viên-PET',1,'PET','Bùi Thanh Kim Ngọc','Lê Thị Viên'),
  ('doi-nu-31-40','Bảng B','Hoàng Thị Bích Thảo / Nguyễn Thị Kim Huế- PVI HOLDINGS',1,'PVI HOLDINGS','Hoàng Thị Bích Thảo','Nguyễn Thị Kim Huế'),
  ('doi-nu-31-40','Bảng B','Đào Hồng Nhung / Hoàng Thái Hà-PVMR',1,'PVMR','Đào Hồng Nhung','Hoàng Thái Hà'),
  ('doi-nu-31-40','Bảng B','Ngô Lê Linh Viên / Trần Hoàng Chi-BĐPOC',1,'BĐPOC','Ngô Lê Linh Viên','Trần Hoàng Chi'),
  ('doi-nu-31-40','Bảng C','Nguyễn Thị Huyền / Nguyễn Thị Thủy-VSP',2,'VSP','Nguyễn Thị Huyền','Nguyễn Thị Thủy'),
  ('doi-nu-31-40','Bảng C','Nguyễn Hồng Vân / Nguyễn Thị Thanh Phương-PVTRANS',2,'PVTRANS','Nguyễn Hồng Vân','Nguyễn Thị Thanh Phương'),
  ('doi-nu-31-40','Bảng C','Bùi Phương Thúy / Trần Lê Na-PVG',2,'PVG','Bùi Phương Thúy','Trần Lê Na'),
  ('doi-nu-31-40','Bảng D','Hoàng Thị Trang / Lê Thị Hồng Nhung-PTSC',2,'PTSC','Hoàng Thị Trang','Lê Thị Hồng Nhung'),
  ('doi-nu-31-40','Bảng D','Phạm Huyền Nga / Trần Thị Hiền-PET',2,'PET','Phạm Huyền Nga','Trần Thị Hiền'),
  ('doi-nu-31-40','Bảng D','Dương Thị Lập / Mai Thị Minh Hà-PVFCCo',2,'PVFCCo','Dương Thị Lập','Mai Thị Minh Hà'),
  ('doi-nu-31-40','Bảng E','Ngô Thị Huyền Trang / Nguyễn Thị Mai Loan-PVMB',3,'PVMB','Ngô Thị Huyền Trang','Nguyễn Thị Mai Loan'),
  ('doi-nu-31-40','Bảng E','Hoàng Phương Thu / Hoàng Thị Sao Mai-VSP',3,'VSP','Hoàng Phương Thu','Hoàng Thị Sao Mai'),
  ('doi-nu-31-40','Bảng E','Nguyễn Thị Hằng / Nguyễn Thị Tuyết Hạnh-PVG',3,'PVG','Nguyễn Thị Hằng','Nguyễn Thị Tuyết Hạnh'),
  ('doi-nu-31-40','Bảng F','Lê Phương Linh / Vũ Thu Hương-PVEP',3,'PVEP','Lê Phương Linh','Vũ Thu Hương'),
  ('doi-nu-31-40','Bảng F','Bùi Thẩm Thuý Hằng / Ngô Thị Hạnh-PVCHEM',3,'PVCHEM','Bùi Thẩm Thuý Hằng','Ngô Thị Hạnh'),
  ('doi-nu-31-40','Bảng F','Dương Thị Nga / Trần Kim Phụng-PVcomBank',3,'PVcomBank','Dương Thị Nga','Trần Kim Phụng'),
  ('doi-nu-41-50','Bảng A','Hà Thị Dung / Nguyễn Thị Anh Thương-PVD',1,'PVD','Hà Thị Dung','Nguyễn Thị Anh Thương'),
  ('doi-nu-41-50','Bảng A','Nguyễn Kiều Chinh / Trầm Ngọc Dung-PVPOWER',1,'PVPOWER','Nguyễn Kiều Chinh','Trầm Ngọc Dung'),
  ('doi-nu-41-50','Bảng A','Lê Thị Cẩm Thu / Nguyễn Thị Nga-VSP',1,'VSP','Lê Thị Cẩm Thu','Nguyễn Thị Nga'),
  ('doi-nu-41-50','Bảng B','Hoàng Thị Hương / Nguyễn Thị Tuyết Nhung-PVOIL',1,'PVOIL','Hoàng Thị Hương','Nguyễn Thị Tuyết Nhung'),
  ('doi-nu-41-50','Bảng B','Đỗ Thị Hưng / Trần Thị Thu Phương-VSP',1,'VSP','Đỗ Thị Hưng','Trần Thị Thu Phương'),
  ('doi-nu-41-50','Bảng B','Nguyễn Hoàng Lan / Nguyễn Thị Hải Yến-PVG',1,'PVG','Nguyễn Hoàng Lan','Nguyễn Thị Hải Yến'),
  ('doi-nu-41-50','Bảng C','Lê Thị Linh / Phùng Thị BìnhPETROCONs',2,null,null,null),
  ('doi-nu-41-50','Bảng C','Hoàng Thị Việt Hà / Mai Thị Thu Hường-PVCHEM',2,'PVCHEM','Hoàng Thị Việt Hà','Mai Thị Thu Hường'),
  ('doi-nu-41-50','Bảng C','Hoàng Hải Hà / Nguyễn Thị Ngọc AnhPVOIL',2,null,null,null),
  ('doi-nu-41-50','Bảng D','Trịnh Hồng Giang / Vũ Thị Hồng-VSP',2,'VSP','Trịnh Hồng Giang','Vũ Thị Hồng'),
  ('doi-nu-41-50','Bảng D','Nguyễn Thị Hải Yến / Vũ Thị Minh Hảo-PVFCCo',2,'PVFCCo','Nguyễn Thị Hải Yến','Vũ Thị Minh Hảo'),
  ('doi-nu-41-50','Bảng D','Đoàn Vũ Nương / Trần Thị Kiều Ngân- PVCombank',2,'PVCombank','Đoàn Vũ Nương','Trần Thị Kiều Ngân'),
  ('doi-nam-nu-tren-51','Bảng A','Đinh Tuấn Anh / Phạm Thị Bích LiênPVEP',1,null,null,null),
  ('doi-nam-nu-tren-51','Bảng A','Bùi Đình Tùng / Lê Anh Thư-PTSC',1,'PTSC','Bùi Đình Tùng','Lê Anh Thư'),
  ('doi-nam-nu-tren-51','Bảng A','Đinh Thúy Quỳnh / Nguyễn Quốc Thành-VSP',1,'VSP','Đinh Thúy Quỳnh','Nguyễn Quốc Thành'),
  ('doi-nam-nu-tren-51','Bảng B','Đào Thị Hòa / Huỳnh Minh TrungVSP',1,null,null,null),
  ('doi-nam-nu-tren-51','Bảng B','Nguyễn Thanh Sơn / Phạm Thị Thủy-BMĐH',1,'BMĐH','Nguyễn Thanh Sơn','Phạm Thị Thủy'),
  ('doi-nam-nu-tren-51','Bảng B','Nguyễn Văn Hướng / Phạm Thị Lệ Minh-PV CHEM',1,'PV CHEM','Nguyễn Văn Hướng','Phạm Thị Lệ Minh'),
  ('doi-nam-nu-tren-51','Bảng C','Hoàng Thị Việt Hoa / Nguyễn Quang Hòa-PTROCONs',2,'PTROCONs','Hoàng Thị Việt Hoa','Nguyễn Quang Hòa'),
  ('doi-nam-nu-tren-51','Bảng C','Nguyễn Văn Hóa / Trần Thị Hồng Tuyết-PVD',2,'PVD','Nguyễn Văn Hóa','Trần Thị Hồng Tuyết'),
  ('doi-nam-nu-tren-51','Bảng C','Đỗ Tấn / Nguyễn Thị Thu Hương-PVG',2,'PVG','Đỗ Tấn','Nguyễn Thị Thu Hương'),
  ('doi-nam-nu-tren-51','Bảng C','Bùi Thị Trúc / Đào Văn Tâm-VSP',2,'VSP','Bùi Thị Trúc','Đào Văn Tâm'),
  ('doi-nu-tren-50','Bảng A','Hà Thị Ánh Huệ / Trần Thị Kim Hoa- PTSC',1,'PTSC','Hà Thị Ánh Huệ','Trần Thị Kim Hoa'),
  ('doi-nu-tren-50','Bảng A','Ng Thị Thanh Hương / Nguyễn Thị Thư- PVFCCo',1,'PVFCCo','Ng Thị Thanh Hương','Nguyễn Thị Thư'),
  ('doi-nu-tren-50','Bảng A','Nguyễn Thị Loan / Nguyễn Thị Thu Mai- VSP',1,'VSP','Nguyễn Thị Loan','Nguyễn Thị Thu Mai'),
  ('doi-nu-tren-50','Bảng A','Đỗ Thị Loan / Hoàng Thị Thu Hương- VSP',1,'VSP','Đỗ Thị Loan','Hoàng Thị Thu Hương'),
  ('doi-nu-tren-50','Bảng A','Nguyễn Thị Oanh / Tạ Thị Thu Hiền-VSP',1,'VSP','Nguyễn Thị Oanh','Tạ Thị Thu Hiền');
insert into public.organizations (code, name_vi, name_en)
select distinct organization_code, organization_code, organization_code from seed_pickleball_pairs where organization_code is not null
on conflict (code) do update set archived_at = null;
insert into public.participants (organization_id, full_name)
select o.id, names.full_name from seed_pickleball_pairs p join public.organizations o on o.code = p.organization_code
cross join lateral (values (p.member_one), (p.member_two)) names(full_name) where names.full_name is not null
and not exists (select 1 from public.participants a where a.organization_id = o.id and a.full_name = names.full_name);
insert into public.groups (tournament_id, name_vi, name_en, sort_order)
select t.id, g.group_name, replace(g.group_name, 'Bảng ', 'Group '), min(g.group_order)
from (values
  ('doi-nam-31-40','Bảng A',1),
  ('doi-nam-31-40','Bảng B',2),
  ('doi-nam-31-40','Bảng C',3),
  ('doi-nam-31-40','Bảng D',4),
  ('doi-nam-31-40','Bảng E',5),
  ('doi-nam-31-40','Bảng F',6),
  ('doi-nam-31-40','Bảng G',7),
  ('doi-nam-31-40','Bảng H',8),
  ('doi-nam-31-40','Bảng I',9),
  ('doi-nam-31-40','Bảng J',10),
  ('doi-nam-31-40','Bảng K',11),
  ('doi-nam-31-40','Bảng L',12),
  ('doi-nam-41-50','Bảng A',1),
  ('doi-nam-41-50','Bảng B',2),
  ('doi-nam-41-50','Bảng C',3),
  ('doi-nam-41-50','Bảng D',4),
  ('doi-nam-41-50','Bảng E',5),
  ('doi-nam-41-50','Bảng F',6),
  ('doi-nam-41-50','Bảng G',7),
  ('doi-nam-41-50','Bảng H',8),
  ('doi-nam-41-50','Bảng I',9),
  ('doi-nam-41-50','Bảng J',10),
  ('doi-nam-duoi-30','Bảng A',1),
  ('doi-nam-duoi-30','Bảng B',2),
  ('doi-nam-duoi-30','Bảng C',3),
  ('doi-nam-duoi-30','Bảng D',4),
  ('doi-nam-duoi-30','Bảng E',5),
  ('doi-nam-duoi-30','Bảng F',6),
  ('doi-nam-duoi-30','Bảng G',7),
  ('doi-nam-duoi-30','Bảng H',8),
  ('doi-nam-duoi-30','Bảng I',9),
  ('doi-nam-duoi-30','Bảng J',10),
  ('doi-nam-duoi-30','Bảng K',11),
  ('doi-nam-nu-31-40','Bảng A',1),
  ('doi-nam-nu-31-40','Bảng B',2),
  ('doi-nam-nu-31-40','Bảng C',3),
  ('doi-nam-nu-31-40','Bảng D',4),
  ('doi-nam-nu-31-40','Bảng E',5),
  ('doi-nam-nu-31-40','Bảng F',6),
  ('doi-nam-nu-31-40','Bảng G',7),
  ('doi-nam-nu-31-40','Bảng H',8),
  ('doi-nam-nu-41-50','Bảng A',1),
  ('doi-nam-nu-41-50','Bảng B',2),
  ('doi-nam-nu-41-50','Bảng C',3),
  ('doi-nam-nu-41-50','Bảng D',4),
  ('doi-nam-nu-41-50','Bảng E',5),
  ('doi-nam-nu-41-50','Bảng F',6),
  ('doi-nam-nu-41-50','Bảng G',7),
  ('doi-nam-nu-duoi-30','Bảng A',1),
  ('doi-nam-nu-duoi-30','Bảng B',2),
  ('doi-nam-nu-duoi-30','Bảng C',3),
  ('doi-nam-nu-duoi-30','Bảng D',4),
  ('doi-nam-nu-duoi-30','Bảng E',5),
  ('doi-nam-nu-duoi-30','Bảng F',6),
  ('doi-nam-nu-duoi-30','Bảng G',7),
  ('doi-nam-nu-tren-51','Bảng A',1),
  ('doi-nam-nu-tren-51','Bảng B',2),
  ('doi-nam-nu-tren-51','Bảng C',3),
  ('doi-nam-tren-51','Bảng A',1),
  ('doi-nam-tren-51','Bảng B',2),
  ('doi-nam-tren-51','Bảng C',3),
  ('doi-nam-tren-51','Bảng D',4),
  ('doi-nam-tren-51','Bảng E',5),
  ('doi-nam-tren-51','Bảng F',6),
  ('doi-nam-tren-51','Bảng G',7),
  ('doi-nam-tren-51','Bảng H',8),
  ('doi-nu-31-40','Bảng A',1),
  ('doi-nu-31-40','Bảng B',2),
  ('doi-nu-31-40','Bảng C',3),
  ('doi-nu-31-40','Bảng D',4),
  ('doi-nu-31-40','Bảng E',5),
  ('doi-nu-31-40','Bảng F',6),
  ('doi-nu-41-50','Bảng A',1),
  ('doi-nu-41-50','Bảng B',2),
  ('doi-nu-41-50','Bảng C',3),
  ('doi-nu-41-50','Bảng D',4),
  ('doi-nu-tren-50','Bảng A',1)) as g(tournament_slug, group_name, group_order)
join public.sports s on s.slug = 'pickleball' join public.tournaments t on t.sport_id = s.id and t.slug = g.tournament_slug
group by t.id, g.group_name on conflict (tournament_id, name_vi) do update set archived_at = null;
insert into public.entries (tournament_id, organization_id, kind, name_vi, name_en)
select t.id, o.id, 'pair', p.pair_name, p.pair_name from (select distinct tournament_slug, pair_name, organization_code from seed_pickleball_pairs) p
join public.sports s on s.slug = 'pickleball' join public.tournaments t on t.sport_id = s.id and t.slug = p.tournament_slug
left join public.organizations o on o.code = p.organization_code
where not exists (select 1 from public.entries e where e.tournament_id = t.id and e.name_vi = p.pair_name);
insert into public.entry_members (entry_id, participant_id, sort_order)
select e.id, a.id, names.sort_order from seed_pickleball_pairs p join public.sports s on s.slug = 'pickleball'
join public.tournaments t on t.sport_id = s.id and t.slug = p.tournament_slug join public.entries e on e.tournament_id = t.id and e.name_vi = p.pair_name
join public.organizations o on o.code = p.organization_code cross join lateral (values (p.member_one, 1), (p.member_two, 2)) names(full_name, sort_order)
join public.participants a on a.organization_id = o.id and a.full_name = names.full_name where names.full_name is not null
on conflict (entry_id, participant_id) do update set archived_at = null;
insert into public.group_entries (group_id, entry_id)
select g.id, e.id from seed_pickleball_pairs p join public.sports s on s.slug = 'pickleball'
join public.tournaments t on t.sport_id = s.id and t.slug = p.tournament_slug join public.groups g on g.tournament_id = t.id and g.name_vi = p.group_name
join public.entries e on e.tournament_id = t.id and e.name_vi = p.pair_name
on conflict (group_id, entry_id) do update set archived_at = null;
-- Match rows intentionally omit time/court: these PDF tables do not state either field.
create temporary table seed_pickleball_fixtures (tournament_slug text, group_name text, home_name text, away_name text, source_page integer, sort_order integer) on commit drop;
insert into seed_pickleball_fixtures values
  ('doi-nam-31-40','Bảng A','Đặng Mạnh Khang / Nguyễn Đình Nam-PVOIL','Nguyễn Hoàng Nghĩa / Phan Xuân Hoàng-PVD',1,1),
  ('doi-nam-31-40','Bảng A','Nguyễn Đức Hiệp / Trần Minh Châu-PVTRANS','Nguyễn Hoàng Nghĩa / Phan Xuân Hoàng-PVD',1,2),
  ('doi-nam-31-40','Bảng A','Đặng Mạnh Khang / Nguyễn Đình Nam-PVOIL','Nguyễn Đức Hiệp / Trần Minh Châu-PVTRANS',1,3),
  ('doi-nam-31-40','Bảng B','Nguyễn Thượng Nghĩa / Phạm Quang Minh-SWPOC','Ngô Hải Đường / Vũ Đức Hòa-BĐPOC',1,4),
  ('doi-nam-31-40','Bảng B','Cù Xuân Huy / Trần Nam Trung-PVFCCo','Ngô Hải Đường / Vũ Đức Hòa-BĐPOC',1,5),
  ('doi-nam-31-40','Bảng B','Nguyễn Thượng Nghĩa / Phạm Quang Minh-SWPOC','Cù Xuân Huy / Trần Nam Trung-PVFCCo',1,6),
  ('doi-nam-31-40','Bảng C','Bùi Bạch Nhựt / Đặng Văn Hoài Linh- PVMP','Đoàn Thanh Lâm / Trịnh Minh Tuấn-PV POWER',2,7),
  ('doi-nam-31-40','Bảng C','Ngô Bảo Trung / Nguyễn Mạnh Cường-PVOIL','Đoàn Thanh Lâm / Trịnh Minh Tuấn-PV POWER',2,8),
  ('doi-nam-31-40','Bảng C','Bùi Bạch Nhựt / Đặng Văn Hoài Linh- PVMP','Ngô Bảo Trung / Nguyễn Mạnh Cường-PVOIL',2,9),
  ('doi-nam-31-40','Bảng D','Đinh Viết Long / Phạm Ngọc Hải-PVD','Nguyễn Bình Phương / Nguyễn Ngọc Thành-PQPOC',2,10),
  ('doi-nam-31-40','Bảng D','Hoàng Ngọc Quý / Nguyễn Minh Tú-PVG','Nguyễn Bình Phương / Nguyễn Ngọc Thành-PQPOC',2,11),
  ('doi-nam-31-40','Bảng D','Đinh Viết Long / Phạm Ngọc Hải-PVD','Nguyễn Bình Phương / Nguyễn Ngọc Thành-PQPOC',2,12),
  ('doi-nam-31-40','Bảng E','Đoàn Đình Kiên / Ngô Thanh BìnhPV POWER','Nguyễn Hữu Tiến / Võ Thế Cường-VSP',3,13),
  ('doi-nam-31-40','Bảng E','Nguyễn Thanh Toàn / Nguyễn Thanh Tùng-PVI','Nguyễn Hữu Tiến / Võ Thế Cường-VSP',3,14),
  ('doi-nam-31-40','Bảng E','Đoàn Đình Kiên / Ngô Thanh BìnhPV POWER','Nguyễn Thanh Toàn / Nguyễn Thanh Tùng-PVI',3,15),
  ('doi-nam-31-40','Bảng F','Hồ Trọng Khiêm / Phan Sỹ Danh-PVD','Nguyễn Văn Tráng / Trương Kiên TrungPVG',3,16),
  ('doi-nam-31-40','Bảng F','Ngô Văn Tuyên / Phạm Văn Nam-PCFCCCo','Nguyễn Văn Tráng / Trương Kiên TrungPVG',3,17),
  ('doi-nam-31-40','Bảng G','Đỗ Xuân Đường / Lê Quang Thái-PVTANS','Đỗ Minh Ngọc / Lê Thành Bi-PVI',4,18),
  ('doi-nam-31-40','Bảng G','Cao Huy Hiệp / Lê Việt Cường-BĐPOC','Đỗ Minh Ngọc / Lê Thành Bi-PVI',4,19),
  ('doi-nam-31-40','Bảng G','Đỗ Xuân Đường / Lê Quang Thái-PVTANS','Cao Huy Hiệp / Lê Việt Cường-BĐPOC',4,20),
  ('doi-nam-31-40','Bảng H','Nguyễn Đức Thuận / Phạm Văn Cường-PVMB','Nguyễn Ngọc Minh / Trần Trung Hiếu-PQPOC',4,21),
  ('doi-nam-31-40','Bảng I','Nguyễn Viết Huy / Tạ Quang Tuấn Anh-PVI','Chu Mạnh Hùng / Nguyễn Hữu Nhân-PVEP',5,22),
  ('doi-nam-31-40','Bảng I','Đỗ Ngọc Vĩnh / Nguyễn Ngọc Khương-NCKHĐT','Chu Mạnh Hùng / Nguyễn Hữu Nhân-PVEP',5,23),
  ('doi-nam-31-40','Bảng I','Nguyễn Viết Huy / Tạ Quang Tuấn Anh-PVI','Đỗ Ngọc Vĩnh / Nguyễn Ngọc Khương-NCKHĐT',5,24),
  ('doi-nam-31-40','Bảng J','Nguyễn Hoàng Phúc / Phan Quang Hùng-PVCom','Hồ Trọng Hải / Nguyễn Hoàng Anh-PVTRAS',5,25),
  ('doi-nam-31-40','Bảng J','Lê Ngọc Quyết / Võ Thái Sơn-PVCFC','Hồ Trọng Hải / Nguyễn Hoàng Anh-PVTRAS',5,26),
  ('doi-nam-31-40','Bảng K','Hàn Văn Long / Nguyễn Tiến Dũng-VSP','Trần Quốc Khương / Trần Việt Linh-PVMB',6,27),
  ('doi-nam-31-40','Bảng K','Nguyễn Ngọc Nhã / Trần Ngọc Trung-BĐPOC','Trần Quốc Khương / Trần Việt Linh-PVMB',6,28),
  ('doi-nam-31-40','Bảng K','Hàn Văn Long / Nguyễn Tiến Dũng-VSP','Nguyễn Ngọc Nhã / Trần Ngọc Trung-BĐPOC',6,29),
  ('doi-nam-31-40','Bảng L','Nguyễn Hoàng Phúc / Phan Quang Hùng-PVCom','Hồ Trọng Hải / Nguyễn Hoàng Anh-PVTRAS',6,30),
  ('doi-nam-31-40','Bảng L','Lê Ngọc Quyết / Võ Thái Sơn-PVCFC','Hồ Trọng Hải / Nguyễn Hoàng Anh-PVTRAS',6,31),
  ('doi-nam-31-40','Bảng L','Nguyễn Hoàng Phúc / Phan Quang Hùng-PVCom','Lê Ngọc Quyết / Võ Thái Sơn-PVCFC',6,32),
  ('doi-nam-41-50','Bảng A','Phan Ngọc Quyết / Trương Tấn Lợi-VSP','Đặng Văn Tuấn / Nguyễn Ngọc Sơn-PQPOC',1,33),
  ('doi-nam-41-50','Bảng A','Bùi Quang Hưng / Nguyễn Quốc HuyPVTRANS','Nguyễn Văn Tuyên / Trần Nghĩa Anh-PVOIL',1,34),
  ('doi-nam-41-50','Bảng A','Phan Ngọc Quyết / Trương Tấn Lợi-VSP','Nguyễn Văn Tuyên / Trần Nghĩa Anh-PVOIL',1,35),
  ('doi-nam-41-50','Bảng A','Bùi Quang Hưng / Nguyễn Quốc HuyPVTRANS','Đặng Văn Tuấn / Nguyễn Ngọc Sơn-PQPOC',1,36),
  ('doi-nam-41-50','Bảng A','Phan Ngọc Quyết / Trương Tấn Lợi-VSP','Bùi Quang Hưng / Nguyễn Quốc HuyPVTRANS',1,37),
  ('doi-nam-41-50','Bảng A','Nguyễn Văn Tuyên / Trần Nghĩa Anh-PVOIL','Đặng Văn Tuấn / Nguyễn Ngọc Sơn-PQPOC',1,38),
  ('doi-nam-41-50','Bảng B','Nguyễn Ngọc Vũ / Ng Xuân Trường-PV POWER','Đoàn Lê Dũng / Nguyễn Công Cường-PET',2,39),
  ('doi-nam-41-50','Bảng B','Đặng Huy Tài / Phan Văn Quang-PVFCCo','Chu Minh Hòa / Lê Trọng Nhân-SWPOC',2,40),
  ('doi-nam-41-50','Bảng B','Nguyễn Ngọc Vũ / Ng Xuân Trường-PV POWER','Chu Minh Hòa / Lê Trọng Nhân-SWPOC',2,41),
  ('doi-nam-41-50','Bảng B','Đặng Huy Tài / Phan Văn Quang-PVFCCo','Đoàn Lê Dũng / Nguyễn Công Cường-PET',2,42),
  ('doi-nam-41-50','Bảng B','Nguyễn Ngọc Vũ / Ng Xuân Trường-PV POWER','Đặng Huy Tài / Phan Văn Quang-PVFCCo',2,43),
  ('doi-nam-41-50','Bảng B','Chu Minh Hòa / Lê Trọng Nhân-SWPOC','Đoàn Lê Dũng / Nguyễn Công Cường-PET',2,44),
  ('doi-nam-41-50','Bảng C','Hoàng Xuân Thoả / Nguyễn Thanh Bằng-PVFCCo','Lê Việt Thường / Nguyễn Mậu Đăng-PVFCCo',3,45),
  ('doi-nam-41-50','Bảng C','Lê Đình Biên / Trần Tuấn An-SWPOC','Lê Văn Thảo / Ngô Minh Hoàng-PVI',3,46),
  ('doi-nam-41-50','Bảng C','Hoàng Xuân Thoả / Nguyễn Thanh Bằng-PVFCCo','Lê Văn Thảo / Ngô Minh Hoàng-PVI',3,47),
  ('doi-nam-41-50','Bảng C','Lê Đình Biên / Trần Tuấn An-SWPOC','Lê Việt Thường / Nguyễn Mậu Đăng-PVFCCo',3,48),
  ('doi-nam-41-50','Bảng C','Hoàng Xuân Thoả / Nguyễn Thanh Bằng-PVFCCo','Lê Đình Biên / Trần Tuấn An-SWPOC',3,49),
  ('doi-nam-41-50','Bảng C','Lê Văn Thảo / Ngô Minh Hoàng-PVI','Lê Việt Thường / Nguyễn Mậu Đăng-PVFCCo',3,50),
  ('doi-nam-41-50','Bảng D','Hoàng Văn Mạnh / Nguyễn Đình Chung-NCKHĐT','Lê Minh Phong / Trần Hoàng Minh-PETROCONs',4,51),
  ('doi-nam-41-50','Bảng D','Nguyễn Văn Tiến / Trịnh Huy Thắng-PVCCHEM','Nguyễn Hoàng Anh / Nguyễn Thành Ba- VSP',4,52),
  ('doi-nam-41-50','Bảng D','Hoàng Văn Mạnh / Nguyễn Đình Chung-NCKHĐT','Nguyễn Hoàng Anh / Nguyễn Thành Ba- VSP',4,53),
  ('doi-nam-41-50','Bảng D','Nguyễn Văn Tiến / Trịnh Huy Thắng-PVCCHEM','Lê Minh Phong / Trần Hoàng Minh-PETROCONs',4,54),
  ('doi-nam-41-50','Bảng D','Hoàng Văn Mạnh / Nguyễn Đình Chung-NCKHĐT','Nguyễn Văn Tiến / Trịnh Huy Thắng-PVCCHEM',4,55),
  ('doi-nam-41-50','Bảng D','Nguyễn Hoàng Anh / Nguyễn Thành Ba- VSP','Lê Minh Phong / Trần Hoàng Minh-PETROCONs',4,56),
  ('doi-nam-41-50','Bảng E','Hoàng Hiệp / Nguyễn Duy Hân-PVOIL','Đỗ Văn Tài / Nguyễn Việt Cường-PVCHEM',5,57),
  ('doi-nam-41-50','Bảng E','Hồ Sỹ Chương / Nguyễn Xuân Thủy-PVEP','Nguyễn Văn Nhung / Phạm Duy Ngọc-PVFCCo',5,58),
  ('doi-nam-41-50','Bảng E','Hoàng Hiệp / Nguyễn Duy Hân-PVOIL','Nguyễn Văn Nhung / Phạm Duy Ngọc-PVFCCo',5,59),
  ('doi-nam-41-50','Bảng E','Hồ Sỹ Chương / Nguyễn Xuân Thủy-PVEP','Đỗ Văn Tài / Nguyễn Việt Cường-PVCHEM',5,60),
  ('doi-nam-41-50','Bảng E','Hoàng Hiệp / Nguyễn Duy Hân-PVOIL','Hồ Sỹ Chương / Nguyễn Xuân Thủy-PVEP',5,61),
  ('doi-nam-41-50','Bảng E','Nguyễn Văn Nhung / Phạm Duy Ngọc-PVFCCo','Đỗ Văn Tài / Nguyễn Việt Cường-PVCHEM',5,62),
  ('doi-nam-41-50','Bảng F','Đặng Quang Tuân / Đinh Trần Trung Kiên-BĐPOC','Bùi Tử An / Dương Chí Trung-NCKHĐT',6,63),
  ('doi-nam-41-50','Bảng F','Nguyễn Văn Sơn / Phạm Văn Thu-PETOCONs','Vũ Anh Tuấn / Vũ Quý Hoàng-VSP',6,64),
  ('doi-nam-41-50','Bảng F','Đặng Quang Tuân / Đinh Trần Trung Kiên-BĐPOC','Vũ Anh Tuấn / Vũ Quý Hoàng-VSP',6,65),
  ('doi-nam-41-50','Bảng F','Nguyễn Văn Sơn / Phạm Văn Thu-PETOCONs','Bùi Tử An / Dương Chí Trung-NCKHĐT',6,66),
  ('doi-nam-41-50','Bảng F','Đặng Quang Tuân / Đinh Trần Trung Kiên-BĐPOC','Nguyễn Văn Sơn / Phạm Văn Thu-PETOCONs',6,67),
  ('doi-nam-41-50','Bảng F','Vũ Anh Tuấn / Vũ Quý Hoàng-VSP','Bùi Tử An / Dương Chí Trung-NCKHĐT',6,68),
  ('doi-nam-41-50','Bảng G','Bùi Ngọc Quyền / Lê Việt Dũng -BĐPOC','Đỗ Trung Thành / Trần Đình Niên- PET',7,69),
  ('doi-nam-41-50','Bảng G','Hoàng Minh Hưng / Nguyễn Tiến Lợi-PQPOC','Nguyễn Văn Đồng / Phạm Quốc Thành-PVCHEM',7,70),
  ('doi-nam-41-50','Bảng G','Bùi Ngọc Quyền / Lê Việt Dũng -BĐPOC','Nguyễn Văn Đồng / Phạm Quốc Thành-PVCHEM',7,71),
  ('doi-nam-41-50','Bảng G','Hoàng Minh Hưng / Nguyễn Tiến Lợi-PQPOC','Đỗ Trung Thành / Trần Đình Niên- PET',7,72),
  ('doi-nam-41-50','Bảng G','Bùi Ngọc Quyền / Lê Việt Dũng -BĐPOC','Hoàng Minh Hưng / Nguyễn Tiến Lợi-PQPOC',7,73),
  ('doi-nam-41-50','Bảng G','Nguyễn Văn Đồng / Phạm Quốc Thành-PVCHEM','Đỗ Trung Thành / Trần Đình Niên- PET',7,74),
  ('doi-nam-41-50','Bảng H','Hà Minh Tuấn / Nguyễn Hồng Giang-PVD','Hồ Anh Khoa / Phạm Chính Hiếu-SWPOC',8,75),
  ('doi-nam-41-50','Bảng H','Nguyễn Thanh Hà / Thái Đào Tuấn Khanh-BĐPOC','Lê Thanh Tùng / Trần Văn Thực-PVOIL',8,76),
  ('doi-nam-41-50','Bảng H','Hà Minh Tuấn / Nguyễn Hồng Giang-PVD','Lê Thanh Tùng / Trần Văn Thực-PVOIL',8,77),
  ('doi-nam-41-50','Bảng H','Nguyễn Thanh Hà / Thái Đào Tuấn Khanh-BĐPOC','Hồ Anh Khoa / Phạm Chính Hiếu-SWPOC',8,78),
  ('doi-nam-41-50','Bảng H','Hà Minh Tuấn / Nguyễn Hồng Giang-PVD','Nguyễn Thanh Hà / Thái Đào Tuấn Khanh-BĐPOC',8,79),
  ('doi-nam-41-50','Bảng H','Lê Thanh Tùng / Trần Văn Thực-PVOIL','Hồ Anh Khoa / Phạm Chính Hiếu-SWPOC',8,80),
  ('doi-nam-41-50','Bảng I','Hoàng Quốc Thành Huy / Tường Duy Quân-PVMR','Đặng Quốc PhonG / Võ khắc Anh Vũ-PQPOC',9,81),
  ('doi-nam-41-50','Bảng I','Nguyễn Văn Bảo / Thới Thành Phủ-PV combank','Dương Bình / Phan Văn Hảo-PVEP',9,82),
  ('doi-nam-41-50','Bảng I','Hoàng Quốc Thành Huy / Tường Duy Quân-PVMR','Dương Bình / Phan Văn Hảo-PVEP',9,83),
  ('doi-nam-41-50','Bảng I','Nguyễn Văn Bảo / Thới Thành Phủ-PV combank','Đặng Quốc PhonG / Võ khắc Anh Vũ-PQPOC',9,84),
  ('doi-nam-41-50','Bảng I','Hoàng Quốc Thành Huy / Tường Duy Quân-PVMR','Nguyễn Văn Bảo / Thới Thành Phủ-PV combank',9,85),
  ('doi-nam-41-50','Bảng I','Dương Bình / Phan Văn Hảo-PVEP','Đặng Quốc PhonG / Võ khắc Anh Vũ-PQPOC',9,86),
  ('doi-nam-tren-51','Bảng A','Lê Kim Long / Lê Trần Hòa-NCKHĐT','Hà Thân Tín / Nguyễn Công Ngọc-PET',1,87),
  ('doi-nam-tren-51','Bảng A','Hoàng Đức Tuấn / Nguyễn Văn Ánh-VSP','Hà Thân Tín / Nguyễn Công Ngọc-PET',1,88),
  ('doi-nam-tren-51','Bảng A','Lê Kim Long / Lê Trần Hòa-NCKHĐT','Hoàng Đức Tuấn / Nguyễn Văn Ánh-VSP',1,89),
  ('doi-nam-tren-51','Bảng B','Nguyễn Tiến Hải / Nguyễn Văn Đức-PVG','Nguyễn Thế Đường / Nguyễn Viết Vượng-PVEP',1,90),
  ('doi-nam-tren-51','Bảng B','Hồ Trọng Lục / Nguyễn Ánh Sao-PVOIL','Nguyễn Thế Đường / Nguyễn Viết Vượng-PVEP',1,91),
  ('doi-nam-tren-51','Bảng B','Nguyễn Tiến Hải / Nguyễn Văn Đức-PVG','Hồ Trọng Lục / Nguyễn Ánh Sao-PVOIL',1,92),
  ('doi-nam-tren-51','Bảng C','Lê Văn Xương / Vũ Đình Thu-BĐPOC','Lê Mạnh Hùng / Nguyễn Tiến Sỹ-PVFCCo',2,93),
  ('doi-nam-tren-51','Bảng C','An Quốc Hưng / Trần Hải Đăng-PVFC','Lê Mạnh Hùng / Nguyễn Tiến Sỹ-PVFCCo',2,94),
  ('doi-nam-tren-51','Bảng C','Lê Văn Xương / Vũ Đình Thu-BĐPOC','An Quốc Hưng / Trần Hải Đăng-PVFC',2,95),
  ('doi-nam-tren-51','Bảng E','Nguyễn Ngọc Minh / Vũ Minh Đức-PVEP','Nguyễn Minh Tân / Trần Hồng Phong- PVMR',3,96),
  ('doi-nam-tren-51','Bảng E','Lê Hồng Hải / Trần Huy Thực-PVG','Nguyễn Minh Tân / Trần Hồng Phong- PVMR',3,97),
  ('doi-nam-tren-51','Bảng E','Nguyễn Ngọc Minh / Vũ Minh Đức-PVEP','Lê Hồng Hải / Trần Huy Thực-PVG',3,98),
  ('doi-nam-tren-51','Bảng F','Nguyễn Thu Phong / Trần Anh Đức-PVOIL','Đinh Minh Tú / Hồ Trường Giang-PVTRANS',4,99),
  ('doi-nam-tren-51','Bảng F','Ngô Đình Chung / Nguyễn Thanh Tịnh-VSP','Đinh Minh Tú / Hồ Trường Giang-PVTRANS',4,100),
  ('doi-nam-tren-51','Bảng F','Nguyễn Thu Phong / Trần Anh Đức-PVOIL','Ngô Đình Chung / Nguyễn Thanh Tịnh-VSP',4,101),
  ('doi-nam-tren-51','Bảng G','Huỳnh Tuấn Kiệt / Nguyễn Quang Vinh-PQPOC','Phạm Xuân Hồng / Trần Văn Hùng-PVOIL',4,102),
  ('doi-nam-tren-51','Bảng H','Bùi Trung Kiên / Nguyễn Văn Sang-PTSC','Đỗ Đoàn Tấn Tài / Ngô Ngọc Trung-PVFCCo',5,103),
  ('doi-nam-tren-51','Bảng H','Lê Hôǹ g Lĩnh / Nguyễn Văn Hải-PVEP','Nguyễn Hữu Lễ / Trần Dũng Tiến-PV POWER',5,104),
  ('doi-nam-tren-51','Bảng H','Bùi Trung Kiên / Nguyễn Văn Sang-PTSC','Nguyễn Hữu Lễ / Trần Dũng Tiến-PV POWER',5,105),
  ('doi-nam-tren-51','Bảng H','Lê Hôǹ g Lĩnh / Nguyễn Văn Hải-PVEP','Đỗ Đoàn Tấn Tài / Ngô Ngọc Trung-PVFCCo',5,106),
  ('doi-nam-tren-51','Bảng H','Bùi Trung Kiên / Nguyễn Văn Sang-PTSC','Lê Hôǹ g Lĩnh / Nguyễn Văn Hải-PVEP',5,107),
  ('doi-nam-tren-51','Bảng H','Nguyễn Hữu Lễ / Trần Dũng Tiến-PV POWER','Đỗ Đoàn Tấn Tài / Ngô Ngọc Trung-PVFCCo',5,108),
  ('doi-nam-nu-duoi-30','Bảng A','Hoàng Linh Anh / Trần Anh Duy-PVOIL','Long Thị Yến Nhi / Vũ Văn Tuấn-PVComBank',1,109),
  ('doi-nam-nu-duoi-30','Bảng A','Lê Hoài Bắc / Nguyễn Hoàng Anh-PVG','Long Thị Yến Nhi / Vũ Văn Tuấn-PVComBank',1,110),
  ('doi-nam-nu-duoi-30','Bảng A','Hoàng Linh Anh / Trần Anh Duy-PVOIL','Lê Hoài Bắc / Nguyễn Hoàng Anh-PVG',1,111),
  ('doi-nam-nu-duoi-30','Bảng B','Huỳnh Thanh Quỳnh Nhi / Lê Khánh Huy-VSP','Lê Thị Tường Vi / Trần Hữu Đăng Khoa-PVTRANS',1,112),
  ('doi-nam-nu-duoi-30','Bảng B','Đỗ Đình Ngọc Tùng / Phan Thị Kim Ngân-PVFCCo','Lê Thị Tường Vi / Trần Hữu Đăng Khoa-PVTRANS',1,113),
  ('doi-nam-nu-duoi-30','Bảng C','Nguyễn Hữu Lam / Nguyễn Thị Diễm Phúc-PVFCCo','Bùi Văn Quảng / Phan Thị Tuyết Ngân-PV POWER',2,114),
  ('doi-nam-nu-duoi-30','Bảng C','Ngo Hoai Nam / Võ Thị Thuỳ Linh-PQPOC','Bùi Văn Quảng / Phan Thị Tuyết Ngân-PV POWER',2,115),
  ('doi-nam-nu-duoi-30','Bảng C','Nguyễn Hữu Lam / Nguyễn Thị Diễm Phúc-PVFCCo','Ngo Hoai Nam / Võ Thị Thuỳ Linh-PQPOC',2,116),
  ('doi-nam-nu-duoi-30','Bảng D','Quách Văn Kiệt / Trương Lê Ngọc Trinh-PET','Nguyễn Quốc Khởi/Phạm Thị Hương-PVG',2,117),
  ('doi-nam-nu-duoi-30','Bảng E','Nguyễn Hải Anh / Trương Hoàng Ngọc-PVOIL','Lê Văn Tuấn / Trịnh Thị Hiền-PTSC',3,118),
  ('doi-nam-nu-duoi-30','Bảng E','Đỗ Thị Mai Trang / Vũ Hùng Anh-VSP','Lê Văn Tuấn / Trịnh Thị Hiền-PTSC',3,119),
  ('doi-nam-nu-duoi-30','Bảng E','Nguyễn Hải Anh / Trương Hoàng Ngọc-PVOIL','Đỗ Thị Mai Trang / Vũ Hùng Anh-VSP',3,120),
  ('doi-nam-nu-duoi-30','Bảng G','Lê Thị Hiền / Trần Tuấn Anh-PVD','Bùi Quang Thanh / Phạm Thị Phương Dung- PVMR',4,121),
  ('doi-nam-nu-duoi-30','Bảng G','Nghiêm Viêt́ Quang / Phạm Thi ̣Hồng- PVEP','Hoàng Lưu Thúy Nga / Ngô Huy Long-VSP',4,122),
  ('doi-nam-nu-duoi-30','Bảng G','Lê Thị Hiền / Trần Tuấn Anh-PVD','Hoàng Lưu Thúy Nga / Ngô Huy Long-VSP',4,123),
  ('doi-nam-nu-duoi-30','Bảng G','Nghiêm Viêt́ Quang / Phạm Thi ̣Hồng- PVEP','Bùi Quang Thanh / Phạm Thị Phương Dung- PVMR',4,124),
  ('doi-nam-nu-duoi-30','Bảng G','Lê Thị Hiền / Trần Tuấn Anh-PVD','Nghiêm Viêt́ Quang / Phạm Thi ̣Hồng- PVEP',4,125),
  ('doi-nam-nu-duoi-30','Bảng G','Hoàng Lưu Thúy Nga / Ngô Huy Long-VSP','Bùi Quang Thanh / Phạm Thị Phương Dung- PVMR',4,126),
  ('doi-nam-nu-31-40','Bảng A','Bùi Duy Thành / Hoàng Khánh Huyền-PVTRANS','Nguyễn Thành Công / Trần Thị Thanh Huyền- VSP',1,127),
  ('doi-nam-nu-31-40','Bảng A','Bùi Thanh Việt/ Mai thanh / Trâm-PVG','Lê Nam / Vũ Thị Hoài Thu-PVMR',1,128),
  ('doi-nam-nu-31-40','Bảng A','Bùi Duy Thành / Hoàng Khánh Huyền-PVTRANS','Lê Nam / Vũ Thị Hoài Thu-PVMR',1,129),
  ('doi-nam-nu-31-40','Bảng A','Bùi Thanh Việt/ Mai thanh / Trâm-PVG','Nguyễn Thành Công / Trần Thị Thanh Huyền- VSP',1,130),
  ('doi-nam-nu-31-40','Bảng A','Bùi Duy Thành / Hoàng Khánh Huyền-PVTRANS','Bùi Thanh Việt/ Mai thanh Trâm- / PVG',1,131),
  ('doi-nam-nu-31-40','Bảng A','Lê Nam / Vũ Thị Hoài Thu-PVMR','Nguyễn Thành Công / Trần Thị Thanh Huyền- VSP',1,132),
  ('doi-nam-nu-31-40','Bảng B','Nguyễn Thị Phượng / Nguyễn Văn Quế-PVcomBank','Nguyễn Thị Loan / Trần Quốc AnhPVCHEM',1,133),
  ('doi-nam-nu-31-40','Bảng B','Thái Thiên Thanh / Vũ Quang Hiển-PVOIL','Đỗ Thị Quỳnh Trang / Nguyễn Thanh Tâm-BĐPOC',1,134),
  ('doi-nam-nu-31-40','Bảng B','Nguyễn Thị Phượng / Nguyễn Văn Quế-PVcomBank','Đỗ Thị Quỳnh Trang / Nguyễn Thanh Tâm-BĐPOC',1,135),
  ('doi-nam-nu-31-40','Bảng B','Thái Thiên Thanh / Vũ Quang Hiển-PVOIL','Nguyễn Thị Loan / Trần Quốc AnhPVCHEM',1,136),
  ('doi-nam-nu-31-40','Bảng B','Nguyễn Thị Phượng / Nguyễn Văn Quế-PVcomBank','Thái Thiên Thanh / Vũ Quang Hiển-PVOIL',1,137),
  ('doi-nam-nu-31-40','Bảng B','Đỗ Thị Quỳnh Trang / Nguyễn Thanh Tâm-BĐPOC','Nguyễn Thị Loan / Trần Quốc AnhPVCHEM',1,138),
  ('doi-nam-nu-31-40','Bảng C','Bùi Anh Tuấn / Nguyễn Hải Nguyên-PVMB','Đoàn Khánh Trình / Phạm Thị Thu Hiên-PVG',2,139),
  ('doi-nam-nu-31-40','Bảng C','Lê thị Tường Vi/ Ng Hoang / Minh-PVTRANS','Đặng Thùy Chi / Vũ Tiến Trung- PVEP',2,140),
  ('doi-nam-nu-31-40','Bảng C','Bùi Anh Tuấn / Nguyễn Hải Nguyên-PVMB','Đặng Thùy Chi / Vũ Tiến Trung- PVEP',2,141),
  ('doi-nam-nu-31-40','Bảng C','Lê thị Tường Vi/ Ng Hoang / Minh-PVTRANS','Đoàn Khánh Trình / Phạm Thị Thu Hiên-PVG',2,142),
  ('doi-nam-nu-31-40','Bảng C','Bùi Anh Tuấn / Nguyễn Hải Nguyên-PVMB','Lê thị Tường Vi/ Ng Hoang / Minh-PVTRANS',2,143),
  ('doi-nam-nu-31-40','Bảng C','Đặng Thùy Chi / Vũ Tiến Trung- PVEP','Đoàn Khánh Trình / Phạm Thị Thu Hiên-PVG',2,144),
  ('doi-nam-nu-31-40','Bảng D','Hồ Văn Linh / Phan Thị Thu-PETRCONs','Phạm Thị Mơ / Phan Ngọc Khánh-PVTRANS',2,145),
  ('doi-nam-nu-31-40','Bảng D','Lê Thị Hà / Nguyễn Ngọc Anh- VSP','Như Ý Nguyễn / Vũ Chí Cường-PQPOC',2,146),
  ('doi-nam-nu-31-40','Bảng D','Hồ Văn Linh / Phan Thị Thu-PETRCONs','Như Ý Nguyễn / Vũ Chí Cường-PQPOC',2,147),
  ('doi-nam-nu-31-40','Bảng D','Lê Thị Hà / Nguyễn Ngọc Anh- VSP','Phạm Thị Mơ / Phan Ngọc Khánh-PVTRANS',2,148),
  ('doi-nam-nu-31-40','Bảng D','Hồ Văn Linh / Phan Thị Thu-PETRCONs','Lê Thị Hà / Nguyễn Ngọc Anh- VSP',2,149),
  ('doi-nam-nu-31-40','Bảng D','Như Ý Nguyễn / Vũ Chí Cường-PQPOC','Phạm Thị Mơ / Phan Ngọc Khánh-PVTRANS',2,150),
  ('doi-nam-nu-31-40','Bảng E','Mai Bảo Ngọc / Vũ Đức Thành-PVMR','Lê Thị Thùy Dung / Võ Tiến Dũng-PVCFC',3,151),
  ('doi-nam-nu-31-40','Bảng E','Doãn Thị Yến / Đỗ Văn Việt- POWER','Nguyễn Thùy Phương / Phan Huy Bình-BĐPOC',3,152),
  ('doi-nam-nu-31-40','Bảng E','Mai Bảo Ngọc / Vũ Đức Thành-PVMR','Nguyễn Thùy Phương / Phan Huy Bình-BĐPOC',3,153),
  ('doi-nam-nu-31-40','Bảng E','Doãn Thị Yến / Đỗ Văn Việt- POWER','Lê Thị Thùy Dung / Võ Tiến Dũng-PVCFC',3,154),
  ('doi-nam-nu-31-40','Bảng E','Mai Bảo Ngọc / Vũ Đức Thành-PVMR','Doãn Thị Yến / Đỗ Văn Việt- POWER',3,155),
  ('doi-nam-nu-31-40','Bảng E','Nguyễn Thùy Phương / Phan Huy Bình-BĐPOC','Lê Thị Thùy Dung / Võ Tiến Dũng-PVCFC',3,156),
  ('doi-nam-nu-31-40','Bảng F','Nguyễn Tân Huyền / Nguyễn Thị Thảo- BMĐH','Nguyễn Thị Thanh Huyền / Phạm Phú Quốc-PVD',3,157),
  ('doi-nam-nu-31-40','Bảng F','Nguyễn Thị Bích Liễu / Trần Quốc Vương-PVcomBank','Nguyễn Thị Hoài Thương / Nguyễn Văn Bính-VSP',3,158),
  ('doi-nam-nu-31-40','Bảng F','Nguyễn Tân Huyền / Nguyễn Thị Thảo- BMĐH','Nguyễn Thị Hoài Thương / Nguyễn Văn Bính-VSP',3,159),
  ('doi-nam-nu-31-40','Bảng F','Nguyễn Thị Bích Liễu / Trần Quốc Vương-PVcomBank','Nguyễn Thị Thanh Huyền / Phạm Phú Quốc-PVD',3,160),
  ('doi-nam-nu-31-40','Bảng F','Nguyễn Tân Huyền / Nguyễn Thị Thảo- BMĐH','Nguyễn Thị Bích Liễu / Trần Quốc Vương-PVcomBank',3,161),
  ('doi-nam-nu-31-40','Bảng F','Nguyễn Thị Hoài Thương / Nguyễn Văn Bính-VSP','Nguyễn Thị Thanh Huyền / Phạm Phú Quốc-PVD',3,162),
  ('doi-nam-nu-31-40','Bảng G','Châu Khiếu Minh / Nguyễn Thị Thanh -NCKHĐT','Lê Thị Ngọc Lan / Nguyễn Hoàng Long-PV POWER',4,163),
  ('doi-nam-nu-31-40','Bảng G','Nguyễn Thị Ngọc Mai / Vũ Xuân HưngPVG','Lê Hoàng / Ngô Bích Ngọc-PVMR',4,164),
  ('doi-nam-nu-31-40','Bảng G','Châu Khiếu Minh / Nguyễn Thị Thanh -NCKHĐT','Lê Hoàng / Ngô Bích Ngọc-PVMR',4,165),
  ('doi-nam-nu-31-40','Bảng G','Nguyễn Thị Ngọc Mai / Vũ Xuân HưngPVG','Lê Thị Ngọc Lan / Nguyễn Hoàng Long-PV POWER',4,166),
  ('doi-nam-nu-31-40','Bảng G','Châu Khiếu Minh / Nguyễn Thị Thanh -NCKHĐT','Nguyễn Thị Ngọc Mai / Vũ Xuân HưngPVG',4,167),
  ('doi-nam-nu-31-40','Bảng G','Lê Hoàng / Ngô Bích Ngọc-PVMR','Lê Thị Ngọc Lan / Nguyễn Hoàng Long-PV POWER',4,168),
  ('doi-nam-nu-31-40','Bảng H','Bùi Thị Hà / Võ Hoàng Long- PET','Nguyễn Hồng Cẩm Nhung / Trương Ngọc CườngPVCHEM',4,169),
  ('doi-nam-nu-31-40','Bảng H','Mai Minh Phương / Phạm Thị Gấm-PVFCCo','Nguyễn Hồng Cẩm Nhung / Trương Ngọc CườngPVCHEM',4,170),
  ('doi-nam-nu-31-40','Bảng H','Bùi Thị Hà / Võ Hoàng Long- PET','Mai Minh Phương / Phạm Thị Gấm-PVFCCo',4,171),
  ('doi-nam-nu-41-50','Bảng A','Hoàng Thị Ngân / Võ Thanh Tịnh-PETROCONs','Nguyễn Thi ̣Hoa / Trần Đức Minh-PVEP',1,172),
  ('doi-nam-nu-41-50','Bảng A','Bùi Thị Phương Nam / Nguyễn Ngọc Phương-PVCHEM','Nguyễn Thi ̣Hoa / Trần Đức Minh-PVEP',1,173),
  ('doi-nam-nu-41-50','Bảng A','Hoàng Thị Ngân / Võ Thanh Tịnh-PETROCONs','Bùi Thị Phương Nam / Nguyễn Ngọc Phương-PVCHEM',1,174),
  ('doi-nam-nu-41-50','Bảng B','Mai Thị Bích Thảo / Nguyễn Văn Tình-BMĐH','Trần Bích Thùy / Trần Thanh Huy-NCKH',1,175),
  ('doi-nam-nu-41-50','Bảng B','Bùi Thị Ngọc Lan / Phạm Văn Dương-PTSC','Trần Bích Thùy / Trần Thanh Huy-NCKH',1,176),
  ('doi-nam-nu-41-50','Bảng B','Mai Thị Bích Thảo / Nguyễn Văn Tình-BMĐH','Bùi Thị Ngọc Lan / Phạm Văn Dương-PTSC',1,177),
  ('doi-nam-nu-41-50','Bảng C','Đỗ Thành Trung / Nguyễn Thị Anh Thảo-PVCFC','Bùi Thị Tố Loan / Lê Văn Đồng-PET',2,178),
  ('doi-nam-nu-41-50','Bảng C','Đoàn Văn Cương / Nguyễn Thị Thùy Dương-PVPMB','Bùi Thị Tố Loan / Lê Văn Đồng-PET',2,179),
  ('doi-nam-nu-41-50','Bảng C','Đỗ Thành Trung / Nguyễn Thị Anh Thảo-PVCFC','Đoàn Văn Cương / Nguyễn Thị Thùy Dương-PVPMB',2,180),
  ('doi-nam-nu-41-50','Bảng D','Nguyễn Thị Thảo / Trần Sơn Anh-VSP','Bùi Hải Bình / Vũ Lê Thu Trang-PVOIL',2,181),
  ('doi-nam-nu-41-50','Bảng D','Nguyễn Như Trường / Phạm Thị Trang Vân-NCKH','Bùi Hải Bình / Vũ Lê Thu Trang-PVOIL',2,182),
  ('doi-nam-nu-41-50','Bảng E','Lê Thu Trang / Nguyễn Tuấn Anh-VSP','Bùi Mạnh Linh / Lý Thúy An-BĐPOC',3,183),
  ('doi-nam-nu-41-50','Bảng E','Nguyễn Thị Thu Hiền / Nguyễn Văn Sáu-PVEP','Bùi Mạnh Linh / Lý Thúy An-BĐPOC',3,184),
  ('doi-nam-nu-41-50','Bảng E','Lê Thu Trang / Nguyễn Tuấn Anh-VSP','Nguyễn Thị Thu Hiền / Nguyễn Văn Sáu-PVEP',3,185),
  ('doi-nam-nu-41-50','Bảng F','Lê Thị Trang / Trần Hữu Trung-PVMR','Tạ Hải Nam / Trần Thị Hoàng Mai-BĐPOC',3,186),
  ('doi-nam-nu-41-50','Bảng F','Nguyễn Văn Dũng / Phạm Thị Hồng Hiền-VSP','Tạ Hải Nam / Trần Thị Hoàng Mai-BĐPOC',3,187),
  ('doi-nam-nu-41-50','Bảng G','Đậu Phi Công / Lê Thị Thanh Hà-PVOIL','Đoàn Văn Trường / Khổng Thị Ái Xuân-PVFCCo',4,188),
  ('doi-nam-nu-41-50','Bảng G','Bùi Thị Thúy Vượng / Nguyễn Xuân Phường-PVEP','Đoàn Văn Trường / Khổng Thị Ái Xuân-PVFCCo',4,189),
  ('doi-nam-nu-41-50','Bảng G','Đậu Phi Công / Lê Thị Thanh Hà-PVOIL','Bùi Thị Thúy Vượng / Nguyễn Xuân Phường-PVEP',4,190),
  ('doi-nam-duoi-30','Bảng A','Hồ Xuân Hảo / Trần Đại Thiệu-VSP','Nguyễn Đức Hùng / Nguyễn Hải BiênPQPOC',1,191),
  ('doi-nam-duoi-30','Bảng A','Lê Đăng Tú / Trần Hữu Long-PVFCCo','Nguyễn Đức Hùng / Nguyễn Hải BiênPQPOC',1,192),
  ('doi-nam-duoi-30','Bảng A','Hồ Xuân Hảo / Trần Đại Thiệu-VSP','Lê Đăng Tú / Trần Hữu Long-PVFCCo',1,193),
  ('doi-nam-duoi-30','Bảng B','Nguyễn Văn Tú / Phạm Văn Hưng-PVFCCo','Đoàn Văn Chúc / Nguyễn Trọng NhânLP1PP',1,194),
  ('doi-nam-duoi-30','Bảng B','Nguyễn Hoàng Văn / Nguyễn Nhật Minh-PVG','Đoàn Văn Chúc / Nguyễn Trọng NhânLP1PP',1,195),
  ('doi-nam-duoi-30','Bảng B','Nguyễn Văn Tú / Phạm Văn Hưng-PVFCCo','Nguyễn Hoàng Văn / Nguyễn Nhật Minh-PVG',1,196),
  ('doi-nam-duoi-30','Bảng C','Nguyễn Minh Tuấn / Trần Công Lê Thắng-VSP','Nguyễn Đức Anh / Nguyễn Văn Sửu-PVCHEM',2,197),
  ('doi-nam-duoi-30','Bảng C','Giáp Văn Tuấn / Hoàng Đình Cương PET','Nguyễn Đức Anh / Nguyễn Văn Sửu-PVCHEM',2,198),
  ('doi-nam-duoi-30','Bảng C','Nguyễn Minh Tuấn / Trần Công Lê Thắng-VSP','Giáp Văn Tuấn / Hoàng Đình Cương PET',2,199),
  ('doi-nam-duoi-30','Bảng D','Lê Quốc Truyền / Trần Minh Hiếu-PVI HOLIDINGS','Huỳnh Hữu Đức / Lê Thanh Bình-PVEP',2,200),
  ('doi-nam-duoi-30','Bảng D','Bùi Tiến Thành / Trần Thái-PVTRAN','Huỳnh Hữu Đức / Lê Thanh Bình-PVEP',2,201),
  ('doi-nam-duoi-30','Bảng E','Đỗ Văn Dương / Trương Hoài Phi-PVD','Lê Quốc Việt Anh / Nguyễn Văn Chung-PVOIL',3,202),
  ('doi-nam-duoi-30','Bảng E','Đỗ Hoàng Nam / Lê Thiện Nhật-PVTRANS','Lê Quốc Việt Anh / Nguyễn Văn Chung-PVOIL',3,203),
  ('doi-nam-duoi-30','Bảng E','Đỗ Văn Dương / Trương Hoài Phi-PVD','Đỗ Hoàng Nam / Lê Thiện Nhật-PVTRANS',3,204),
  ('doi-nam-duoi-30','Bảng F','Nguyễn Xuân Ngọc / Phạm Quang Hiếu-PVE','Cao Ngọc Tuấn / Lê Trọng Nghĩa-PVEP',3,205),
  ('doi-nam-duoi-30','Bảng G','Nguyễn Hùng Cường / Nguyễn Minh ThuậnPVPOWER','lương thúc chính / Nguyễn Minh Hải-PQPOC',4,206),
  ('doi-nam-duoi-30','Bảng G','Trần Hữu Đăng Khoa/Phạm Đức Trọng-PVT','lương thúc chính / Nguyễn Minh Hải-PQPOC',4,207),
  ('doi-nam-duoi-30','Bảng G','Nguyễn Hùng Cường / Nguyễn Minh ThuậnPVPOWER','Trần Hữu Đăng Khoa/Phạm Đức Trọng-PVTRANS',4,208),
  ('doi-nam-duoi-30','Bảng I','Nguyễn Hoàng Quý / Nguyễn Thanh Tuấn-PVD','Nguyễn Hùng Binh / Nguyễn Minh Thuấn-PVCHEM',5,209),
  ('doi-nam-duoi-30','Bảng I','Nguyễn Mạnh Hưng / Nguyễn Xuân Hiến-BĐPOC','Nguyễn Hùng Binh / Nguyễn Minh Thuấn-PVCHEM',5,210),
  ('doi-nam-duoi-30','Bảng I','Nguyễn Hoàng Quý / Nguyễn Thanh Tuấn-PVD','Nguyễn Mạnh Hưng / Nguyễn Xuân Hiến-BĐPOC',5,211),
  ('doi-nam-duoi-30','Bảng K','Bùi Khắc Anh Tuấn / Phạm Hồng Phương-PET','Bùi Trung Kiên / Phan Phước Gia-PVEP',6,212),
  ('doi-nam-duoi-30','Bảng K','Bùi Ngô Phúc Minh / Đặng Việt An-MNĐH PETRO','Bùi Trung Kiên / Phan Phước Gia-PVEP',6,213),
  ('doi-nam-duoi-30','Bảng K','Bùi Khắc Anh Tuấn / Phạm Hồng Phương-PET','Bùi Ngô Phúc Minh / Đặng Việt An-MNĐH PETRO',6,214),
  ('doi-nu-31-40','Bảng A','Lê Thúy Nga / Nguyễn Thị Bích Liên-VSP','Bùi Thanh Kim Ngọc / Lê Thị Viên-PET',1,215),
  ('doi-nu-31-40','Bảng A','Đinh Ngân Đài / Nguyễn Thùy Chi-PVEP','Bùi Thanh Kim Ngọc / Lê Thị Viên-PET',1,216),
  ('doi-nu-31-40','Bảng A','Lê Thúy Nga / Nguyễn Thị Bích Liên-VSP','Đinh Ngân Đài / Nguyễn Thùy Chi-PVEP',1,217),
  ('doi-nu-31-40','Bảng B','Hoàng Thị Bích Thảo / Nguyễn Thị Kim Huế- PVI / HOLDINGS','Ngô Lê Linh Viên / Trần Hoàng Chi-BĐPOC',1,218),
  ('doi-nu-31-40','Bảng B','Đào Hồng Nhung / Hoàng Thái Hà-PVMR','Ngô Lê Linh Viên / Trần Hoàng Chi-BĐPOC',1,219),
  ('doi-nu-31-40','Bảng B','Hoàng Thị Bích Thảo / Nguyễn Thị Kim Huế- PVI / HOLDINGS','Đào Hồng Nhung / Hoàng Thái Hà-PVMR',1,220),
  ('doi-nu-31-40','Bảng C','Nguyễn Thị Huyền / Nguyễn Thị Thủy-VSP','Bùi Phương Thúy / Trần Lê Na-PVG',2,221),
  ('doi-nu-31-40','Bảng C','Nguyễn Hồng Vân / Nguyễn Thị Thanh Phương- / PVTRANS','Bùi Phương Thúy / Trần Lê Na-PVG',2,222),
  ('doi-nu-31-40','Bảng C','Nguyễn Thị Huyền / Nguyễn Thị Thủy-VSP','Bùi Phương Thúy / Trần Lê Na-PVG',2,223),
  ('doi-nu-31-40','Bảng D','Hoàng Thị Trang / Lê Thị Hồng Nhung-PTSC','Dương Thị Lập / Mai Thị Minh Hà-PVFCCo',2,224),
  ('doi-nu-31-40','Bảng D','Phạm Huyền Nga / Trần Thị Hiền-PET','Dương Thị Lập / Mai Thị Minh Hà-PVFCCo',2,225),
  ('doi-nu-31-40','Bảng D','Hoàng Thị Trang / Lê Thị Hồng Nhung-PTSC','Dương Thị Lập / Mai Thị Minh Hà-PVFCCo',2,226),
  ('doi-nu-31-40','Bảng E','Ngô Thị Huyền Trang / Nguyễn Thị Mai Loan-PVMB','Nguyễn Thị Hằng / Nguyễn Thị Tuyết Hạnh-PVG',3,227),
  ('doi-nu-31-40','Bảng E','Hoàng Phương Thu / Hoàng Thị Sao Mai-VSP','Nguyễn Thị Hằng / Nguyễn Thị Tuyết Hạnh-PVG',3,228),
  ('doi-nu-31-40','Bảng E','Ngô Thị Huyền Trang / Nguyễn Thị Mai Loan-PVMB','Hoàng Phương Thu / Hoàng Thị Sao Mai-VSP',3,229),
  ('doi-nu-31-40','Bảng F','Lê Phương Linh / Vũ Thu Hương-PVEP','Dương Thị Nga / Trần Kim Phụng-PVcomBank',3,230),
  ('doi-nu-31-40','Bảng F','Bùi Thẩm Thuý Hằng / Ngô Thị Hạnh-PVCHEM','Dương Thị Nga / Trần Kim Phụng-PVcomBank',3,231),
  ('doi-nu-31-40','Bảng F','Lê Phương Linh / Vũ Thu Hương-PVEP','Bùi Thẩm Thuý Hằng / Ngô Thị Hạnh-PVCHEM',3,232),
  ('doi-nu-41-50','Bảng A','Hà Thị Dung / Nguyễn Thị Anh Thương-PVD','Lê Thị Cẩm Thu / Nguyễn Thị Nga-VSP',1,233),
  ('doi-nu-41-50','Bảng A','Nguyễn Kiều Chinh / Trầm Ngọc Dung-PVPOWER','Lê Thị Cẩm Thu / Nguyễn Thị Nga-VSP',1,234),
  ('doi-nu-41-50','Bảng A','Hà Thị Dung / Nguyễn Thị Anh Thương-PVD','Nguyễn Kiều Chinh / Trầm Ngọc Dung-PVPOWER',1,235),
  ('doi-nu-41-50','Bảng B','Hoàng Thị Hương / Nguyễn Thị Tuyết Nhung-PVOIL','Nguyễn Hoàng Lan / Nguyễn Thị Hải Yến-PVG',1,236),
  ('doi-nu-41-50','Bảng B','Đỗ Thị Hưng / Trần Thị Thu Phương-VSP','Nguyễn Hoàng Lan / Nguyễn Thị Hải Yến-PVG',1,237),
  ('doi-nu-41-50','Bảng B','Hoàng Thị Hương / Nguyễn Thị Tuyết Nhung-PVOIL','Đỗ Thị Hưng / Trần Thị Thu Phương-VSP',1,238),
  ('doi-nu-41-50','Bảng C','Lê Thị Linh / Phùng Thị BìnhPETROCONs','Hoàng Hải Hà / Nguyễn Thị Ngọc AnhPVOIL',2,239),
  ('doi-nu-41-50','Bảng C','Hoàng Thị Việt Hà / Mai Thị Thu Hường-PVCHEM','Hoàng Hải Hà / Nguyễn Thị Ngọc AnhPVOIL',2,240),
  ('doi-nu-41-50','Bảng C','Lê Thị Linh / Phùng Thị BìnhPETROCONs','Hoàng Thị Việt Hà / Mai Thị Thu Hường-PVCHEM',2,241),
  ('doi-nu-41-50','Bảng D','Trịnh Hồng Giang / Vũ Thị Hồng-VSP','Đoàn Vũ Nương / Trần Thị Kiều Ngân- PVCombank',2,242),
  ('doi-nu-41-50','Bảng D','Nguyễn Thị Hải Yến / Vũ Thị Minh Hảo-PVFCCo','Đoàn Vũ Nương / Trần Thị Kiều Ngân- PVCombank',2,243),
  ('doi-nu-41-50','Bảng D','Trịnh Hồng Giang / Vũ Thị Hồng-VSP','Nguyễn Thị Hải Yến / Vũ Thị Minh Hảo-PVFCCo',2,244),
  ('doi-nam-nu-tren-51','Bảng A','Đinh Tuấn Anh / Phạm Thị Bích LiênPVEP','Đinh Thúy Quỳnh / Nguyễn Quốc Thành-VSP',1,245),
  ('doi-nam-nu-tren-51','Bảng A','Bùi Đình Tùng / Lê Anh Thư-PTSC','Đinh Thúy Quỳnh / Nguyễn Quốc Thành-VSP',1,246),
  ('doi-nam-nu-tren-51','Bảng A','Đinh Tuấn Anh / Phạm Thị Bích LiênPVEP','Bùi Đình Tùng / Lê Anh Thư-PTSC',1,247),
  ('doi-nam-nu-tren-51','Bảng B','Đào Thị Hòa / Huỳnh Minh TrungVSP','Nguyễn Văn Hướng / Phạm Thị Lệ Minh-PV CHEM',1,248),
  ('doi-nam-nu-tren-51','Bảng B','Nguyễn Thanh Sơn / Phạm Thị Thủy-BMĐH','Nguyễn Văn Hướng / Phạm Thị Lệ Minh-PV CHEM',1,249),
  ('doi-nam-nu-tren-51','Bảng B','Đào Thị Hòa / Huỳnh Minh TrungVSP','Nguyễn Thanh Sơn / Phạm Thị Thủy-BMĐH',1,250),
  ('doi-nam-nu-tren-51','Bảng C','Hoàng Thị Việt Hoa / Nguyễn Quang Hòa-PTROCONs','Bùi Thị Trúc / Đào Văn Tâm-VSP',2,251),
  ('doi-nam-nu-tren-51','Bảng C','Nguyễn Văn Hóa / Trần Thị Hồng Tuyết-PVD','Đỗ Tấn / Nguyễn Thị Thu Hương-PVG',2,252),
  ('doi-nam-nu-tren-51','Bảng C','Hoàng Thị Việt Hoa / Nguyễn Quang Hòa-PTROCONs','Nguyễn Văn Hóa / Trần Thị Hồng Tuyết-PVD',2,253),
  ('doi-nam-nu-tren-51','Bảng C','Đỗ Tấn / Nguyễn Thị Thu Hương-PVG','Bùi Thị Trúc / Đào Văn Tâm-VSP',2,254),
  ('doi-nam-nu-tren-51','Bảng C','Hoàng Thị Việt Hoa / Nguyễn Quang Hòa-PTROCONs','Đỗ Tấn / Nguyễn Thị Thu Hương-PVG',2,255),
  ('doi-nam-nu-tren-51','Bảng C','Nguyễn Văn Hóa / Trần Thị Hồng Tuyết-PVD','Bùi Thị Trúc / Đào Văn Tâm-VSP',2,256),
  ('doi-nu-tren-50','Bảng A','Hà Thị Ánh Huệ / Trần Thị Kim Hoa- PTSC','Nguyễn Thị Oanh / Tạ Thị Thu Hiền-VSP',1,257),
  ('doi-nu-tren-50','Bảng A','Nguyễn Thị Loan / Nguyễn Thị Thu Mai- VSP','Đỗ Thị Loan / Hoàng Thị Thu Hương- VSP',1,258),
  ('doi-nu-tren-50','Bảng A','Hà Thị Ánh Huệ / Trần Thị Kim Hoa- PTSC','Đỗ Thị Loan / Hoàng Thị Thu Hương- VSP',1,259),
  ('doi-nu-tren-50','Bảng A','Ng Thị Thanh Hương / Nguyễn Thị Thư- PVFCCo','Nguyễn Thị Oanh / Tạ Thị Thu Hiền-VSP',1,260),
  ('doi-nu-tren-50','Bảng A','Hà Thị Ánh Huệ / Trần Thị Kim Hoa- PTSC','Nguyễn Thị Loan / Nguyễn Thị Thu Mai- VSP',1,261),
  ('doi-nu-tren-50','Bảng A','Ng Thị Thanh Hương / Nguyễn Thị Thư- PVFCCo','Đỗ Thị Loan / Hoàng Thị Thu Hương- VSP',1,262),
  ('doi-nu-tren-50','Bảng A','Hà Thị Ánh Huệ / Trần Thị Kim Hoa- PTSC','Ng Thị Thanh Hương / Nguyễn Thị Thư- PVFCCo',1,263),
  ('doi-nu-tren-50','Bảng A','Nguyễn Thị Loan / Nguyễn Thị Thu Mai- VSP','Nguyễn Thị Oanh / Tạ Thị Thu Hiền-VSP',1,264),
  ('doi-nu-tren-50','Bảng A','Đỗ Thị Loan / Hoàng Thị Thu Hương- VSP','Nguyễn Thị Oanh / Tạ Thị Thu Hiền-VSP',1,265),
  ('doi-nu-tren-50','Bảng A','Ng Thị Thanh Hương / Nguyễn Thị Thư- PVFCCo','Nguyễn Thị Loan / Nguyễn Thị Thu Mai- VSP',1,266);
insert into public.fixtures (tournament_id, group_id, status, round_vi, round_en, round_order)
select t.id, g.id, 'scheduled', 'Vòng bảng', 'Group stage', p.sort_order from seed_pickleball_fixtures p
join public.sports s on s.slug = 'pickleball' join public.tournaments t on t.sport_id = s.id and t.slug = p.tournament_slug
join public.groups g on g.tournament_id = t.id and g.name_vi = p.group_name
where exists (select 1 from public.entries e where e.tournament_id = t.id and e.name_vi = p.home_name)
and exists (select 1 from public.entries e where e.tournament_id = t.id and e.name_vi = p.away_name)
and not exists (select 1 from public.fixtures f where f.tournament_id = t.id and f.group_id = g.id and f.round_order = p.sort_order);
insert into public.fixture_entries (fixture_id, entry_id, side)
select f.id, e.id, x.side from seed_pickleball_fixtures p join public.sports s on s.slug = 'pickleball'
join public.tournaments t on t.sport_id = s.id and t.slug = p.tournament_slug join public.groups g on g.tournament_id = t.id and g.name_vi = p.group_name
join public.fixtures f on f.tournament_id = t.id and f.group_id = g.id and f.round_order = p.sort_order
cross join lateral (values (p.home_name, 'home'), (p.away_name, 'away')) x(pair_name, side)
join public.entries e on e.tournament_id = t.id and e.name_vi = x.pair_name
on conflict (fixture_id, entry_id) do update set archived_at = null;

