export type AdminEntity = keyof typeof adminEntities;
export type AdminField = { name: string; label: string; type?: "number" | "datetime-local" | "textarea" | "date" };

export const adminEntities = {
  media: { title: "Thư viện ảnh / Gallery", fields: [{name:"storage_path",label:"Storage path"},{name:"kind",label:"gallery/hero/logo/content"},{name:"sport_id",label:"Môn thể thao / Sport"},{name:"title_vi",label:"Tiêu đề VI"},{name:"title_en",label:"Title EN"},{name:"alt_vi",label:"Alt VI"},{name:"alt_en",label:"Alt EN"},{name:"album_vi",label:"Nhóm ảnh VI"},{name:"album_en",label:"Album EN"},{name:"filter_tag",label:"Bộ lọc cũ / Legacy filter"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
  contacts: { title: "Liên hệ / Contacts", fields: [{name:"label_vi",label:"Nhãn VI"},{name:"label_en",label:"Label EN"},{name:"value",label:"Giá trị / Value"},{name:"href",label:"Liên kết / Link"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
  footer_links: { title: "Footer", fields: [{name:"label_vi",label:"Nhãn VI"},{name:"label_en",label:"Label EN"},{name:"href",label:"Liên kết / Link"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
  sports: { title: "Môn thể thao / Sports", fields: [{name:"slug",label:"Slug"},{name:"name_vi",label:"Tên VI"},{name:"name_en",label:"Name EN"},{name:"emoji",label:"Icon"},{name:"description_vi",label:"Mô tả VI",type:"textarea"},{name:"description_en",label:"Description EN",type:"textarea"},{name:"rules_vi",label:"Thể lệ VI",type:"textarea"},{name:"rules_en",label:"Rules EN",type:"textarea"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
  tournaments: { title: "Giải & hạng mục / Tournaments", fields: [{name:"sport_id",label:"Môn thể thao / Sport"},{name:"slug",label:"Slug"},{name:"name_vi",label:"Tên VI"},{name:"name_en",label:"Name EN"},{name:"category_vi",label:"Hạng mục VI"},{name:"category_en",label:"Category EN"},{name:"gender",label:"Giới tính / Gender"},{name:"format_vi",label:"Thể thức VI",type:"textarea"},{name:"format_en",label:"Format EN",type:"textarea"},{name:"rules_vi",label:"Thể lệ VI",type:"textarea"},{name:"rules_en",label:"Rules EN",type:"textarea"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
  organizations: { title: "Đơn vị / Organizations", fields: [{name:"code",label:"Mã / Code"},{name:"name_vi",label:"Tên VI"},{name:"name_en",label:"Name EN"},{name:"logo_path",label:"Logo path"},{name:"leaderboard_rank",label:"Hạng BXH",type:"number"},{name:"gold_medals",label:"Huy chương vàng",type:"number"},{name:"silver_medals",label:"Huy chương bạc",type:"number"},{name:"bronze_medals",label:"Huy chương đồng",type:"number"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
  participants: { title: "Vận động viên / Athletes", fields: [{name:"organization_id",label:"Đơn vị / Organization"},{name:"full_name",label:"Họ tên"},{name:"full_name_en",label:"English name"},{name:"gender",label:"Giới tính / Gender"},{name:"birth_date",label:"Ngày sinh / Date of birth",type:"date"}] },
  entries: { title: "Đội, cặp, cá nhân / Entries", fields: [{name:"tournament_id",label:"Hạng mục / Tournament"},{name:"organization_id",label:"Đơn vị / Organization"},{name:"kind",label:"Loại: individual/pair/team"},{name:"name_vi",label:"Tên VI"},{name:"name_en",label:"Name EN"},{name:"seed_number",label:"Seed",type:"number"},{name:"bib_number",label:"Số áo / Bib"}] },
  entry_members: { title: "Thành viên đội / Entry members", fields: [{name:"entry_id",label:"Đội, cặp, cá nhân / Entry"},{name:"participant_id",label:"Vận động viên / Athlete"},{name:"role_vi",label:"Vai trò VI"},{name:"role_en",label:"Role EN"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
  venues: { title: "Địa điểm / Venues", fields: [{name:"name_vi",label:"Tên VI"},{name:"name_en",label:"Name EN"},{name:"address_vi",label:"Địa chỉ VI"},{name:"address_en",label:"Address EN"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
  courts: { title: "Sân, làn / Courts & lanes", fields: [{name:"venue_id",label:"Địa điểm / Venue"},{name:"name_vi",label:"Tên VI"},{name:"name_en",label:"Name EN"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
  groups: { title: "Bảng đấu / Groups", fields: [{name:"tournament_id",label:"Hạng mục / Tournament"},{name:"name_vi",label:"Tên VI"},{name:"name_en",label:"Name EN"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
  group_entries: { title: "Đội trong bảng / Group entries", fields: [{name:"group_id",label:"Bảng đấu / Group"},{name:"entry_id",label:"Đội, cặp, cá nhân / Entry"},{name:"seed_order",label:"Seed",type:"number"}] },
  fixtures: { title: "Lịch & trận đấu / Fixtures", fields: [{name:"tournament_id",label:"Hạng mục / Tournament"},{name:"group_id",label:"Bảng đấu / Group"},{name:"venue_id",label:"Địa điểm / Venue"},{name:"court_id",label:"Sân, làn / Court"},{name:"starts_at",label:"Bắt đầu / Starts",type:"datetime-local"},{name:"ends_at",label:"Kết thúc / Ends",type:"datetime-local"},{name:"status",label:"Trạng thái / Status"},{name:"round_vi",label:"Vòng VI"},{name:"round_en",label:"Round EN"},{name:"round_order",label:"Round order",type:"number"},{name:"bracket_position",label:"Bracket position",type:"number"},{name:"next_fixture_id",label:"Trận kế tiếp / Next fixture"},{name:"result_summary_vi",label:"Kết quả VI",type:"textarea"},{name:"result_summary_en",label:"Result EN",type:"textarea"},{name:"winner_entry_id",label:"Đội thắng / Winner"}] },
  fixture_entries: { title: "Đối thủ, làn & điểm / Fixture entries", fields: [{name:"fixture_id",label:"Trận đấu / Fixture"},{name:"entry_id",label:"Đội, cặp, cá nhân / Entry"},{name:"side",label:"Side: home/away"},{name:"lane",label:"Làn / Lane",type:"number"},{name:"seed_order",label:"Seed",type:"number"},{name:"score",label:"Tỷ số / Score"},{name:"score_numeric",label:"Điểm số / Numeric score",type:"number"},{name:"rank",label:"Hạng / Rank",type:"number"},{name:"result_detail",label:"Chi tiết JSON",type:"textarea"}] },
  standings: { title: "Bảng xếp hạng / Standings", fields: [{name:"tournament_id",label:"Hạng mục / Tournament"},{name:"group_id",label:"Bảng đấu / Group"},{name:"entry_id",label:"Đội, cặp, cá nhân / Entry"},{name:"played",label:"P",type:"number"},{name:"won",label:"W",type:"number"},{name:"drawn",label:"D",type:"number"},{name:"lost",label:"L",type:"number"},{name:"score_for",label:"Score for",type:"number"},{name:"score_against",label:"Score against",type:"number"},{name:"points",label:"Điểm / Points",type:"number"},{name:"rank",label:"Hạng / Rank",type:"number"},{name:"note_vi",label:"Ghi chú VI",type:"textarea"},{name:"note_en",label:"Note EN",type:"textarea"}] },
  awards: { title: "Huy chương & giải phụ / Awards", fields: [{name:"sport_id",label:"Môn thể thao / Sport"},{name:"tournament_id",label:"Hạng mục / Tournament"},{name:"entry_id",label:"Đội, cặp, cá nhân / Entry"},{name:"participant_id",label:"Vận động viên / Athlete"},{name:"organization_id",label:"Đơn vị / Organization"},{name:"title_vi",label:"Tên giải VI"},{name:"title_en",label:"Award EN"},{name:"medal",label:"gold/silver/bronze/special"},{name:"sort_order",label:"Thứ tự / Order",type:"number"}] },
} as const satisfies Record<string, { title: string; fields: readonly AdminField[] }>;
